<?php
/*
  Generated by Manuigniter v2.0
  www.manuigniter.com
 */
class Acceso_vascular extends CI_Controller {
    private $session_data = "";
    function __construct() {
        parent::__construct();
        $this->load->model('Acceso_vascular_model');
        $this->load->model('Paciente_model');
        $this->load->model('Registro_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Muestrs todo el acceso_vascular de un determinado registro!.
     */
    public function historial($paciente_id = 0) {
        if($this->acceso(17)){
            try {
                $data["rol"] = $this->session_data['rol'];
                $data['registro'] = $this->Registro_model->getlast_registropaciente($paciente_id);
                $data['paciente'] = $this->Paciente_model->get_paciente($paciente_id);
                $data['acceso_vascular'] = $this->Acceso_vascular_model->get_historialacceso($paciente_id);
                $data['_view'] = 'acceso_vascular/historial';
                $this->load->view('layouts/main', $data);
            } catch (Exception $ex) {
                throw new Exception('Acceso vascular Controller : Error in index function - ' . $ex);
            }
        }
    }
    
    function registrar_accesovascular(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'registro_id' => $this->input->post('registro_id'),
                    'paciente_id' => $this->input->post('paciente_id'),
                    'avascular_nombre' => $this->input->post('avascular_nombre'),
                    'avascular_detalle' => $this->input->post('avascular_detalle'),
                );
                $avascular_id = $this->Acceso_vascular_model->add_acceso_vascular($params);
            echo json_encode($avascular_id);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
}
