<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Documentacion extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Documentacion_model');
 } 
 /*
* Listing of documentacion
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['documentacion'] = $this->Documentacion_model->get_all_documentacion();
      $data['_view'] = 'documentacion/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Documentacion Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new documentacion
  */
 function add()
 {  
try{
      $params = array(
       'paciente_id'=> $this->input->post('paciente_id'),
       'documentacion_descripcion'=> $this->input->post('documentacion_descripcion'),
       'documentacion_foto1'=> $this->input->post('documentacion_foto1'),
       'documentacion_foto2'=> $this->input->post('documentacion_foto2'),
       'documentacion_foto3'=> $this->input->post('documentacion_foto3'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $documentacion_id= $this->Documentacion_model->add_documentacion($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('documentacion/index');
        }
        else
        { 
           $data['_view'] = 'documentacion/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Documentacion Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a documentacion
 */
 public function edit($documentacion_id)
 {   
  try{
   $data['documentacion'] = $this->Documentacion_model->get_documentacion($documentacion_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['documentacion']['documentacion_id']))
      {
        $params = array(
           'paciente_id'=> $this->input->post('paciente_id'),
           'documentacion_descripcion'=> $this->input->post('documentacion_descripcion'),
           'documentacion_foto1'=> $this->input->post('documentacion_foto1'),
           'documentacion_foto2'=> $this->input->post('documentacion_foto2'),
           'documentacion_foto3'=> $this->input->post('documentacion_foto3'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Documentacion_model->update_documentacion($documentacion_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('documentacion/index');
           }
           else
          {
              $data['_view'] = 'documentacion/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The documentacion you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Documentacion Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting documentacion
  */
  function remove($documentacion_id)
   {
    try{
      $documentacion = $this->Documentacion_model->get_documentacion($documentacion_id);
  // check if the documentacion exists before trying to delete it
       if(isset($documentacion['documentacion_id']))
       {
         $this->Documentacion_model->delete_documentacion($documentacion_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('documentacion/index');
       }
       else
       show_error('The documentacion you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Documentacion Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a documentacion
 */
 public function view_more($documentacion_id)
 {   
try{
   $data['documentacion'] = $this->Documentacion_model->get_documentacion($documentacion_id);
     if(isset($data['documentacion']['documentacion_id']))
      {
              $data['_view'] = 'documentacion/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The documentacion you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Documentacion Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of documentacion
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['documentacion'] = $this->Documentacion_model->get_all_documentacion_by_cat($column_name,$value_id);
      $data['_view'] = 'documentacion/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- documentacion
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Documentacion_model->update_documentacion($id,$params);
   $data['noof_page'] = 0;
  $data['documentacion'] = $this->Documentacion_model->get_all_documentacion();
  $this->load->view('documentacion/index',$data);
}
 }
