<?php
/*
  Generated by Manuigniter v2.0
  www.manuigniter.com
 */
class Forma extends CI_Controller {
    function __construct() {
        parent::__construct();
        $this->load->model('Forma_model');
    }
    
    /*
     * Listing of forma
     */
    public function index() {
        try {
            $data['forma'] = $this->Forma_model->get_all_forma();
            $data['_view'] = 'forma/index';
            $this->load->view('layouts/main', $data);
        } catch (Exception $ex) {
            throw new Exception('Forma Controller : Error in index function - ' . $ex);
        }
    }

    /*
     * Adding a new forma
     */
    function add() {
        try {
            $params = array(
                'forma_nombre' => $this->input->post('forma_nombre'),
            );
            $this->load->library('upload');
            $this->load->library('form_validation');
            if (isset($_POST) && count($_POST) > 0) {
                $forma_id = $this->Forma_model->add_forma($params);
                redirect('forma/index');
            } else {
                $data['_view'] = 'forma/add';
                $this->load->view('layouts/main', $data);
            }
        } catch (Exception $ex) {
            throw new Exception('Forma Controller : Error in add function - ' . $ex);
        }
    }

    /*
     * Editing a forma
     */
    public function edit($forma_id) {
        try {
            $data['forma'] = $this->Forma_model->get_forma($forma_id);
            $this->load->library('upload');
            $this->load->library('form_validation');
            if (isset($data['forma']['forma_id'])) {
                $params = array(
                    'forma_nombre' => $this->input->post('forma_nombre'),
                );
                if (isset($_POST) && count($_POST) > 0) {
                    $this->Forma_model->update_forma($forma_id, $params);
                    redirect('forma/index');
                } else {
                    $data['_view'] = 'forma/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else
                show_error('The forma you are trying to edit does not exist.');
        } catch (Exception $ex) {
            throw new Exception('Forma Controller : Error in edit function - ' . $ex);
        }
    }

    /*
     * Deleting forma
     */
    /*function remove($forma_id) {
        try {
            $forma = $this->Forma_model->get_forma($forma_id);
            // check if the forma exists before trying to delete it
            if (isset($forma['forma_id'])) {
                $this->Forma_model->delete_forma($forma_id);
                $this->session->set_flashdata('alert_msg', '<div class="alert alert-success text-center">Succesfully Removed.</div>');
                redirect('forma/index');
            } else
                show_error('The forma you are trying to delete does not exist.');
        } catch (Exception $ex) {
            throw new Exception('Forma Controller : Error in remove function - ' . $ex);
        }
    }*/
    
}
