<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Medicamento extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Medicamento_model');
 } 
 /*
* Listing of medicamento
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['medicamento'] = $this->Medicamento_model->get_all_medicamento();
      $data['_view'] = 'medicamento/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Medicamento Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new medicamento
  */
 function add()
 {  
try{
      $params = array(
       'medicamento_codigo'=> $this->input->post('medicamento_codigo'),
       'medicamento_nombre'=> $this->input->post('medicamento_nombre'),
       'medicamento_forma'=> $this->input->post('medicamento_forma'),
       'medicamento_concentracion'=> $this->input->post('medicamento_concentracion'),
       'medicamento_cantidad'=> $this->input->post('medicamento_cantidad'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $medicamento_id= $this->Medicamento_model->add_medicamento($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('medicamento/index');
        }
        else
        { 
           $data['_view'] = 'medicamento/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Medicamento Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a medicamento
 */
 public function edit($medicamento_id)
 {   
  try{
   $data['medicamento'] = $this->Medicamento_model->get_medicamento($medicamento_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['medicamento']['medicamento_id']))
      {
        $params = array(
           'medicamento_codigo'=> $this->input->post('medicamento_codigo'),
           'medicamento_nombre'=> $this->input->post('medicamento_nombre'),
           'medicamento_forma'=> $this->input->post('medicamento_forma'),
           'medicamento_concentracion'=> $this->input->post('medicamento_concentracion'),
           'medicamento_cantidad'=> $this->input->post('medicamento_cantidad'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Medicamento_model->update_medicamento($medicamento_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('medicamento/index');
           }
           else
          {
              $data['_view'] = 'medicamento/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The medicamento you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Medicamento Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting medicamento
  */
  function remove($medicamento_id)
   {
    try{
      $medicamento = $this->Medicamento_model->get_medicamento($medicamento_id);
  // check if the medicamento exists before trying to delete it
       if(isset($medicamento['medicamento_id']))
       {
         $this->Medicamento_model->delete_medicamento($medicamento_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('medicamento/index');
       }
       else
       show_error('The medicamento you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Medicamento Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a medicamento
 */
 public function view_more($medicamento_id)
 {   
try{
   $data['medicamento'] = $this->Medicamento_model->get_medicamento($medicamento_id);
     if(isset($data['medicamento']['medicamento_id']))
      {
              $data['_view'] = 'medicamento/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The medicamento you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Medicamento Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of medicamento
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['medicamento'] = $this->Medicamento_model->get_all_medicamento_by_cat($column_name,$value_id);
      $data['_view'] = 'medicamento/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- medicamento
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Medicamento_model->update_medicamento($id,$params);
   $data['noof_page'] = 0;
  $data['medicamento'] = $this->Medicamento_model->get_all_medicamento();
  $this->load->view('medicamento/index',$data);
}
 }
