<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Medicacion extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Medicacion_model');
 } 
 /*
* Listing of medicacion
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['medicacion'] = $this->Medicacion_model->get_all_medicacion();
      $data['_view'] = 'medicacion/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Medicacion Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new medicacion
  */
 function add()
 {  
try{
      $params = array(
       'sesion_id'=> $this->input->post('sesion_id'),
       'medicamento_id'=> $this->input->post('medicamento_id'),
       'medicacion_cantidad'=> $this->input->post('medicacion_cantidad'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('medicacion/index');
        }
        else
        { 
           $data['_view'] = 'medicacion/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Medicacion Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a medicacion
 */
 public function edit($medicacion_id)
 {   
  try{
   $data['medicacion'] = $this->Medicacion_model->get_medicacion($medicacion_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['medicacion']['medicacion_id']))
      {
        $params = array(
           'sesion_id'=> $this->input->post('sesion_id'),
           'medicamento_id'=> $this->input->post('medicamento_id'),
           'medicacion_cantidad'=> $this->input->post('medicacion_cantidad'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Medicacion_model->update_medicacion($medicacion_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('medicacion/index');
           }
           else
          {
              $data['_view'] = 'medicacion/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The medicacion you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Medicacion Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting medicacion
  */
  function remove($medicacion_id)
   {
    try{
      $medicacion = $this->Medicacion_model->get_medicacion($medicacion_id);
  // check if the medicacion exists before trying to delete it
       if(isset($medicacion['medicacion_id']))
       {
         $this->Medicacion_model->delete_medicacion($medicacion_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('medicacion/index');
       }
       else
       show_error('The medicacion you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Medicacion Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a medicacion
 */
 public function view_more($medicacion_id)
 {   
try{
   $data['medicacion'] = $this->Medicacion_model->get_medicacion($medicacion_id);
     if(isset($data['medicacion']['medicacion_id']))
      {
              $data['_view'] = 'medicacion/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The medicacion you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Medicacion Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of medicacion
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['medicacion'] = $this->Medicacion_model->get_all_medicacion_by_cat($column_name,$value_id);
      $data['_view'] = 'medicacion/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- medicacion
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Medicacion_model->update_medicacion($id,$params);
   $data['noof_page'] = 0;
  $data['medicacion'] = $this->Medicacion_model->get_all_medicacion();
  $this->load->view('medicacion/index',$data);
}
 }
