<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Reportes extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();

        $this->load->model('Reporte_ing_egr_model');
        $this->load->model('Ingreso_model');
        $this->load->model('Empresa_model');
        $this->load->model('Tratamiento_model');
        $this->load->model('Informe_mensual_model');
        $this->load->model('Acceso_vascular_model');
        $this->load->model('Medicamento_model');
        $this->load->model('Medicacion_model');
        $this->load->model('Registro_model');
        $this->load->model('Certificado_medico_model');
        $this->load->model('Anemia_glicemia_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }

    } 
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of cliente
     */
    function index()
    {
        if($this->acceso(141)){
        $this->load->model('Empresa_model');
        $data['all_empresa'] = $this->Empresa_model->get_all_empresa();
        
        $data['tipousuario_id']  = $this->session_data['tipousuario_id'];
        $data['usuario_id']  = $this->session_data['usuario_id'];
        $data['usuario_nombre']  = $this->session_data['usuario_nombre'];
        $this->load->model('Usuario_model');
        
        $this->load->model('Parametro_model');
        $data['parametro'] = $this->Parametro_model->get_parametros();

        $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/index';

        $this->load->view('layouts/main',$data);
        }
    }
    
    /*
     * Reporte del Detalle de Procedimiento de Hemodiálisis
     */
    function detalle_procedimiento($sesion_id)
    {
        if($this->acceso(54)){
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Detalle_hora_model');
            $data['page_title'] = "Detalle Procedimiento";

            $this->load->model('Sesion_model');
            $sesion = $this->Sesion_model->get_sesion($sesion_id);
            $eltratamiento_id = $sesion["tratamiento_id"];
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($sesion['tratamiento_id']);

            $cantidad = $this->Sesion_model->getcount_sesiontratamiento($eltratamiento_id);
            $total_sesiones = $this->Sesion_model->get_sesionesnumeradas($eltratamiento_id);
            foreach ($total_sesiones as $lasesion){
                if($lasesion["sesion_id"] == $sesion_id){
                    $sesion_numero = $lasesion["numeracion"];
                    break;
                }
            }
            //$sesion_numero = $sesion["sesion_numero"];

            if($sesion_numero % 2 == 0){ //numero de sesion es par
                $data['sesion'] = $this->Sesion_model->get_otrasesion($eltratamiento_id, ($sesion_numero-1));
                $data['detalle_hora'] = $this->Detalle_hora_model->get_detalle_horasesionactivas($data['sesion']['sesion_id']);
                $data['sesion2'] =  $sesion;
                $data['detalle_hora2'] = $this->Detalle_hora_model->get_detalle_horasesionactivas($sesion_id);
                $data['_view'] = 'reportes/detalle_procedimiento';
            }else{ //numero de sesion es impar
                $data['sesion'] =  $sesion;
                if($sesion_numero == $cantidad){
                    $data['detalle_hora'] = $this->Detalle_hora_model->get_detalle_horasesionactivas($sesion_id);
                    $data['_view'] = 'reportes/detalle_pultimoimpar';
                }else{
                    $data['detalle_hora'] = $this->Detalle_hora_model->get_detalle_horasesionactivas($sesion_id);
                    $data['sesion2'] = $this->Sesion_model->get_otrasesion($eltratamiento_id, ($sesion_numero+1));
                    $data['detalle_hora2'] = $this->Detalle_hora_model->get_detalle_horasesionactivas($data['sesion2']['sesion_id']);
                    $data['_view'] = 'reportes/detalle_procedimiento';
                }
            }

            $this->load->view('layouts/main',$data);
        }
    }
    
    /*
     * Reporte de las sesiones dado un tratamiento!.
     */
    function reportesesiones($tratamiento_id)
    {
        if($this->acceso(50)){
            $this->load->model('Sesion_model');
            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
            $data['sesiones'] = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento_id);

            $total_sesion = sizeof($data['sesiones']);
            $acceso_vascular = "";
            if($total_sesion > 0){
                $sesion_cateter = $data['sesiones'][$total_sesion-1]["sesion_cateter"];
                $sesion_fistula = $data['sesiones'][$total_sesion-1]["sesion_fistula"];
                if($sesion_cateter != "" && $sesion_cateter != null){
                    $acceso_vascular = "CATETER - ".$sesion_cateter;
                }
                if($sesion_fistula != "" && $sesion_fistula != null){
                    $acceso_vascular = "FISTULA ARTERIO VENOSA - ".$sesion_fistula;
                }
            }

            $data['acceso_vascular'] = $acceso_vascular;

            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();

            $data['page_title'] = "Reporte de sesiones";
            $data['_view'] = 'reportes/reportesesiones';

            $this->load->view('layouts/main',$data);
        }
    }
    
    /*
     * Reporte del Informe Clinico Mensual
     */
    function informecmensual($tratamiento_id)
    {
        if($this->acceso(51)){
            $this->load->model('Sesion_model');
            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
            $data['sesiones'] = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento_id);
            $data['informe_mensual'] = $this->Informe_mensual_model->getall_informe_mensualtratamiento($tratamiento_id);

            $data['acceso_vascular'] = $this->Acceso_vascular_model->get_ultimoa_vascularregistro($data['tratamiento']['registro_id']);

            $peso_seco = "";
            $total_sesion = sizeof($data['sesiones']);
            if($total_sesion > 0){
                $peso_seco = $data['sesiones'][$total_sesion-1]["sesion_pesoseco"];
            }
            $data['peso_seco'] = $peso_seco;
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();

            $data['page_title'] = "Informe clinico mensual";
            $data['_view'] = 'reportes/informecmensual';

            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Reporte del Informe Clinico Mensual
     */
    function medinsumos($tratamiento_id)
    {
        if($this->acceso(55)){
            $this->load->model('Sesion_model');
            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
            $data['registro'] = $this->Registro_model->get_registro($data['tratamiento']["registro_id"]);
            $data['sesiones'] = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento_id);
            $data['informe_mensual'] = $this->Informe_mensual_model->getall_informe_mensualtratamiento($tratamiento_id);
            $data['medicamento_insumo'] = $this->Medicamento_model->get_all_medicamentoid();

            if(isset($data['sesiones'][0]["avascular_id"])){
                $data['acceso_vascular'] = $this->Acceso_vascular_model->get_acceso_vascular($data['sesiones'][0]["avascular_id"]);
            }else{
                $data['acceso_vascular'] = "";
            }

            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();

            $data['page_title'] = "Medicamentos e insumos medicos otorgados y autorizados";
            $data['_view'] = 'reportes/medinsumos';

            $this->load->view('layouts/main',$data);
        }
    }
    
    /* obtiene el ultimo informe mensual de un tratamiento */
    function obtener_medicamentousado(){
        try{
            if($this->input->is_ajax_request()){
                $sesion_id = $this->input->post('sesion_id');
                $medicamento_id = $this->input->post('medicamento_id');
                $medicacion = $this->Medicacion_model->get_medicamento_sesion($sesion_id, $medicamento_id);
            echo json_encode($medicacion);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
     * Reporte del Certificado medico Mensual
     */
    function certificadomedico($certmedico_id)
    {
        if($this->acceso(53)){
            $this->load->model('Sesion_model');
            $data['certificado_medico'] = $this->Certificado_medico_model->get_certificado_medico($certmedico_id);
            $tratamiento_id = $data['certificado_medico']['tratamiento_id'];
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento_id);
            $data['sesiones'] = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);


            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
            $data['informe_mensual'] = $this->Informe_mensual_model->getall_informe_mensualtratamiento($tratamiento_id);

            $data['acceso_vascular'] = $this->Acceso_vascular_model->get_ultimoa_vascularregistro($data['tratamiento']['registro_id']);

            $peso_seco = "";
            $total_sesion = sizeof($data['sesiones']);
            if($total_sesion > 0){
                $peso_seco = $data['sesiones'][$total_sesion-1]["sesion_pesoseco"];
            }
            $data['peso_seco'] = $peso_seco;
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();

            $data['page_title'] = "Informe clinico mensual";
            $data['_view'] = 'reportes/certificadomedico';

            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Informe de Anemia y Glicemia
     */
    function infanemiaglicemia($tratamiento_id)
    {
        if($this->acceso(52)){
        $this->load->model('Sesion_model');
            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
            //$data['sesiones'] = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento_id);
            $data['anemia_glicemia'] = $this->Anemia_glicemia_model->getall_anemia_glicemiatratamiento($tratamiento_id);
            //$data['informe_mensual'] = $this->Informe_mensual_model->getall_informe_mensualtratamiento($tratamiento_id);

            /*$data['acceso_vascular'] = $this->Acceso_vascular_model->get_ultimoa_vascularregistro($data['tratamiento']['registro_id']);

            $peso_seco = "";
            $total_sesion = sizeof($data['sesiones']);
            if($total_sesion > 0){
                $peso_seco = $data['sesiones'][$total_sesion-1]["sesion_pesoseco"];
            }
            $data['peso_seco'] = $peso_seco;
            */
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();

            $data['page_title'] = "Informe clinico mensual";
            $data['_view'] = 'reportes/infanemiaglicemia';

            $this->load->view('layouts/main',$data);
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*
     * Listing of cliente
     */
    function movimientodiario()
    {
        if($this->acceso(141)){
        $this->load->model('Empresa_model');
        $data['empresa'] = $this->Empresa_model->get_all_empresa();
        
        $data['tipousuario_id']  = $this->session_data['tipousuario_id'];
        $data['usuario_id']  = $this->session_data['usuario_id'];
        $data['usuario_nombre']  = $this->session_data['usuario_nombre'];
        $this->load->model('Usuario_model');
        
        $rolusuario = $this->session_data['rol'];
        $data['tienepermiso'] = $rolusuario[171-1]['rolusuario_asignado'];        
        
        $this->load->model('Parametro_model');
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $this->load->model('Moneda_model');
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/reportediario';

        $this->load->view('layouts/main',$data);
        }
    }

    function graficas()
    {
        if($this->acceso(157)){
            $data['empresa'] = $this->Empresa_model->get_all_empresa();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['page_title'] = "Reportes";
            $data['_view'] = 'reportes/graficas';
            $this->load->view('layouts/main',$data);
           // redirect('', 'refresh');
        }
    }

    function graficas2()
    {
        if($this->acceso(157)){
            $data['empresa'] = $this->Empresa_model->get_all_empresa();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['page_title'] = "Reportes";
            $data['_view'] = 'reportes/graficas2';
            $this->load->view('layouts/main',$data);
           // redirect('', 'refresh');
        }
    }
 public function getUltimoDiaMes($elAnio,$elMes) {
     return date("d",(mktime(0,0,0,$elMes+1,1,$elAnio)-1));
    }

function mes($anio,$mes)
{
        $primer_dia=1;
        $ultimo_dia=$this->getUltimoDiaMes($anio,$mes);
        $fecha_inicial=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$primer_dia) );
        $fecha_final=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$ultimo_dia) );
        
        $fechas = "SELECT compra_fecha, round(compra_totalfinal,2) as compra_totalfinal FROM compra where compra.compra_fecha >= '".$anio."-".$mes."-01' and  compra.compra_fecha <= '".$anio."-".$mes."-31' ";
        $result= $this->db->query($fechas)->result_array();
        
        $fechasven = "SELECT venta_fecha, round(venta_total,2) as venta_total FROM venta where venta.venta_fecha >= '".$anio."-".$mes."-01' and  venta.venta_fecha <= '".$anio."-".$mes."-31' ";
        $resultven= $this->db->query($fechasven)->result_array();
        //$result=$data['result'];
        $ct=count($result);

        for($d=1;$d<=$ultimo_dia;$d++){
            $registros[$d]=0;
            $registrosven[$d]=0;     
        }

        foreach($result as $res){
        $diasel=intval(date("d",strtotime($res['compra_fecha']) ) );
        
        $suma=$res['compra_totalfinal'];
        
        $registros[$diasel]+=$suma;    
        }

        foreach($resultven as $resven){
        $diaselven=intval(date("d",strtotime($resven['venta_fecha']) ) );
        
        $sumave=$resven['venta_total'];
       
        $registrosven[$diaselven]+=$sumave;    
        }

        $data=array("totaldias"=>$ultimo_dia, "registrosdia" =>$registros, "registrosven" =>$registrosven);
        echo   json_encode($data);
        /*$anio = $this->input->post('anio');   1555891200
        $mes = $this->input->post('fecha2'); 
*/
        
}

// -------------------------------------------------------------------------------------------------
function mes_usuario($anio,$mes,$usuario_id)
{
        $primer_dia=1;
        $ultimo_dia=$this->getUltimoDiaMes($anio,$mes);
        $fecha_inicial=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$primer_dia) );
        $fecha_final=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$ultimo_dia) );
        // $fechas = "SELECT compra_fecha, round(compra_totalfinal,2) as compra_totalfinal FROM compra where compra.compra_fecha >= '".$anio."-".$mes."-01' and  compra.compra_fecha <= '".$anio."-".$mes."-31' ";
        $fechas = "SELECT date(pedido_fecha), round(p.pedido_total,2) as pedido_total
                    FROM pedido as p
                    where p.pedido_fecha >= '".$anio."-".$mes."-01' 
                    and p.pedido_fecha <= '".$anio."-".$mes."-31'
                    and p.regusuario_id = ".$usuario_id.";";
        $result= $this->db->query($fechas)->result_array();
        $fechasven = "SELECT v.venta_fecha, round(v.venta_total,2) as venta_total 
                        FROM venta as v 
                        where v.venta_fecha >= '".$anio."-".$mes."-01' 
                        and  v.venta_fecha <= '".$anio."-".$mes."-31'
                        and v.usuario_id = ".$usuario_id.";";
        $resultven= $this->db->query($fechasven)->result_array();
        //$result=$data['result'];
        $ct=count($result);

        for($d=1;$d<=$ultimo_dia;$d++){
            $registros[$d]=0;
            $registrosven[$d]=0;     
        }

        foreach($result as $res){
            $diasel=intval(date("d",strtotime($res['date(pedido_fecha)']) ) );
            
            $suma=$res['pedido_total'];
            
            $registros[$diasel]+=$suma;    
        }

        foreach($resultven as $resven){
            $diaselven=intval(date("d",strtotime($resven['venta_fecha']) ) );
            
            $sumave=$resven['venta_total'];
        
            $registrosven[$diaselven]+=$sumave;    
        }

        // foreach($resultpro as $respro){
        //     $diaPro = intval(date("d", strtotime($respro['producto_fecha'])));
        //     $sumpro = $respro['producto_total'];
        //     $registrospro[$diaPro] += $sumpro;
        // }

        $data=array("totaldias"=>$ultimo_dia, "registrosdia" =>$registros, "registrosven" =>$registrosven);
        echo   json_encode($data);
        /*$anio = $this->input->post('anio');   1555891200
        $mes = $this->input->post('fecha2'); 
*/
        
}
// -------------------------------------------------------------------------------------------------

function proven($anio,$mes)
{
        $primer_dia=1;
        $ultimo_dia=$this->getUltimoDiaMes($anio,$mes);
        $numero=10;
        $fecha_inicial=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$primer_dia) );
        $fecha_final=date("Y-m-d H:i:s", strtotime($anio."-".$mes."-".$ultimo_dia) );
        $productos="SELECT i.producto_id, i.producto_nombre, SUM(dv.detalleven_cantidad) as cantidades FROM detalle_venta dv LEFT JOIN venta v on dv.venta_id = v.venta_id LEFT JOIN inventario i on dv.producto_id = i.producto_id WHERE v.venta_fecha>='2019-06-01' and v.venta_fecha<='2019-06-30' GROUP BY dv.producto_id ORDER BY cantidades DESC limit 10";
        $produc= $this->db->query($productos)->result_array();
        //$result=$data['result'];
        

        for($d=1;$d<=$numero;$d++){
            $registros[$d]=0;
            
        }
       
        foreach($produc as $tve){
        $prosel=intval($tve['producto_id']);
        
        $suma=$tve['cantidades'];
        
        $registros[$prosel]=$suma;    
        }

        

        $data=array("totaldias"=>$numero, "registrosdia" =>$registros);
        echo   json_encode($data);
        /*$anio = $this->input->post('anio');   1555891200
        $mes = $this->input->post('fecha2'); 
*/
        
}

function torta($anio,$mes)
{
               
        
        $ventausuario = "SELECT COUNT(DISTINCT usuario_id) as 'distusu' FROM venta where venta.venta_fecha >= '".$anio."-".$mes."-01' and  venta.venta_fecha <= '".$anio."-".$mes."-31' ";
        $usve = $this->db->query($ventausuario)->row_array();
        $numusu=$usve['distusu'];

        $id_usuarios = "SELECT DISTINCT v.usuario_id, u.usuario_nombre FROM venta v, usuario u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and v.usuario_id=u.usuario_id ";
        $usuarios= $this->db->query($id_usuarios)->result_array();



        $totalventas = "SELECT  usuario_id, SUM(venta_total) as 'totalventas' FROM venta where venta.venta_fecha >= '".$anio."-".$mes."-01' and  venta.venta_fecha <= '".$anio."-".$mes."-31' GROUP BY usuario_id";
        $tove= $this->db->query($totalventas)->result_array();
        
        

        foreach($tove as $tve){
        $ususel=intval($tve['usuario_id']);
        
        $suma=round($tve['totalventas'],2);
        
        $registros[$ususel]=$suma;    
        }
       
               
        $data=array("totaltipos"=>$numusu, "tipos" =>$usuarios, "numerodepubli" =>$registros);
        echo   json_encode($data);
        
        
}

function torta2($anio,$mes)
{
               
        
        $ventausuario = "SELECT COUNT(DISTINCT cliente_id) as 'distusu',SUM(venta_total) as 'totalventas' FROM venta where venta.venta_fecha >= '".$anio."-".$mes."-01' and  venta.venta_fecha <= '".$anio."-".$mes."-31' ORDER by totalventas limit 10";
        $usve = $this->db->query($ventausuario)->row_array();
        $numusu=10;

        $id_usuarios = "SELECT DISTINCT v.cliente_id, u.cliente_nombre,SUM(venta_total) as 'totalventas' FROM venta v, cliente u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and v.cliente_id=u.cliente_id GROUP BY cliente_id ORDER by totalventas desc limit 10";
        $usuarios= $this->db->query($id_usuarios)->result_array();



        $totalventas = "SELECT DISTINCT v.cliente_id, SUM(venta_total) as 'totalventas' FROM venta v, cliente u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and v.cliente_id=u.cliente_id GROUP BY cliente_id ORDER by totalventas desc limit 10";
        $tove= $this->db->query($totalventas)->result_array();
        
        

        foreach($usuarios as $tve){
        $ususel=intval($tve['cliente_id']);
        
        $suma=round($tve['totalventas'],2);
        
        $registros[$ususel]=$suma;    
        }
       
       
       
        
        $data=array("totaltipos"=>$numusu, "tipos" =>$usuarios, "numerodepubli" =>$registros);
        echo   json_encode($data);
        
        
}
function torta3($anio,$mes)
{
               
        
        $numusu2=10;

        $id_usuarios = "SELECT DISTINCT dv.producto_id, u.producto_nombre,SUM(dv.detalleven_cantidad) as 'totalventas' FROM detalle_venta dv, venta v, producto u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and dv.venta_id= v.venta_id and dv.producto_id=u.producto_id GROUP BY u.producto_id ORDER by totalventas desc limit 10";
        $usuarios2= $this->db->query($id_usuarios)->result_array();


        foreach($usuarios2 as $tve){
        $ususel=intval($tve['producto_id']);
        
        $suma=round($tve['totalventas'],2);
        
        $registros[$ususel]=$suma;    
        }
       
          
        $data=array("totaltipos"=>$numusu2, "tipos" =>$usuarios2, "numerodepubli" =>$registros);
        echo   json_encode($data);
        
        
}
    /*

     * Reporte de Ingresos y Salidas

     */

    function buscarlosreportes()
    {
        if($this->acceso(141)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reportes($valfecha1, $valfecha2, $usuario_id);
            /*$detalles = $this->Reporte_ing_egr_model->get_detalleventas_reporte($valfecha1, $valfecha2, $usuario_id);
            $ventas   = $this->Reporte_ing_egr_model->get_reportes($valfecha1, $valfecha2, $usuario_id);
            $datos=array("ventas" => $ventas, "detalles" => $detalles);*/
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }

    function buscarporfecha()
    {
        if($this->acceso(141)){
            
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
                $datos = $this->Reporte_ing_egr_model->get_reportemovimiento($valfecha1, $valfecha2, $usuario_id);
            /*if ($fecha1 == 0){
                
            }else{
                $datos = $this->Reporte_ing_egr_model->get_reportemovimientodia();
                
            }*/
            
            /*$detalles = $this->Reporte_ing_egr_model->get_detalleventas_reporte($valfecha1, $valfecha2, $usuario_id);
            $ventas   = $this->Reporte_ing_egr_model->get_reportes($valfecha1, $valfecha2, $usuario_id);
            $datos=array("ventas" => $ventas, "detalles" => $detalles);*/
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }
    
    function buscardiario()
    {
        if($this->acceso(141)){
            
        if ($this->input->is_ajax_request()) {

           

            $datos = $this->Reporte_ing_egr_model->get_reportemovimientodia();
                
            
            
            /*$detalles = $this->Reporte_ing_egr_model->get_detalleventas_reporte($valfecha1, $valfecha2, $usuario_id);
            $ventas   = $this->Reporte_ing_egr_model->get_reportes($valfecha1, $valfecha2, $usuario_id);
            $datos=array("ventas" => $ventas, "detalles" => $detalles);*/
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }



    /*

     * Menu de Reportes de Compras

     */

    function comprareportes()

    {

        if($this->acceso(137)){


        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/comprareportes';

        $this->load->view('layouts/main',$data);

        }

            
    }



    /*

     * Menu de Reportes de Ventas

     */

    function ventareportes()

    {

        if($this->acceso(1)){
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/ventareportes';

        $this->load->view('layouts/main',$data);

        }

          
    }



    /*

     * Menu de Reportes de Servicios

     */

    function servicioreportes()
    {

        if($this->acceso(142)){
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/servicioreportes';

        $this->load->view('layouts/main',$data);

        }


    }
    
    function planillacaja()
    {
        if($this->acceso(1)){
                $this->load->model('Empresa_model');
                $data['all_empresa'] = $this->Empresa_model->get_all_empresa();

                $this->load->model('Usuario_model');

                $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();

        /*

                $fecha1  = Date("Y-m-d");

                $fecha2  = $fecha1;

                $data['ingresos'] = $this->Reporte_ing_egr_model->get_reportes($fecha1, $fecha2);

        */
                $data['page_title'] = "Reportes";
                $data['_view'] = 'reportes/planillacaja';

                $this->load->view('layouts/main',$data);

        }

           

    }
    
    function reptotaling_efectivo()
    {
        if($this->acceso(1)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reptotaling_efectivo($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
          
    }

    /* ************************Reporte total de ventas*******************************+ */
    function reptotal_ventas()
    {
       if($this->acceso(1)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reptotal_ventas($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
           
    }
    /* ************************Reporte total de cobros de Creditos*******************************+ */
    function reptotal_cobroscredito()
    {
        if($this->acceso(1)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reptotal_cobroscredito($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
           
    }
    /* ************Reporte total de Egreso de efectivo******************************* */
    function reptotal_egresoefectivo()
    {
        if($this->acceso(1)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reptotalegr_efectivo($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
          
    }
    
    /* ************Reporte total de Egreso de Compras******************************* */
    function reptotal_egresocompra()
    {
        if($this->acceso(1)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reptotalegr_compras($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }
    
    function reportesformapago()
    {
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $formapago = $this->input->post('formapago'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            if($formapago == 1){
                $datos = $this->Reporte_ing_egr_model->get_repefectivo_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }elseif($formapago == 2){
                $datos = $this->Reporte_ing_egr_model->get_repdebito_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }elseif($formapago == 3){
                $datos = $this->Reporte_ing_egr_model->get_reptransban_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }elseif($formapago == 4){
                $datos = $this->Reporte_ing_egr_model->get_reptarjcredito_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }elseif($formapago == 5){
                $datos = $this->Reporte_ing_egr_model->get_repcheque_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }elseif($formapago == 61){
                $datos = $this->Reporte_ing_egr_model->get_repcredito_ventas($valfecha1, $valfecha2, $usuario_id);
                echo json_encode($datos);
            }
        }   
        else
        {                 
            show_404();
        }
            
    }
    
    function egresorep()
    {
        if($this->acceso(138)){
        $data['usuario_nombre'] = $this->session_data['usuario_nombre'];
        $data['usuario_id'] = $this->session_data['usuario_id'];
        $this->load->model('Empresa_model');
        $data['all_empresa'] = $this->Empresa_model->get_all_empresa();
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/egresorep';

        $this->load->view('layouts/main',$data);

        }

            
    }
    
    function reportegreso()
    {
        if($this->acceso(138)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_egresoreportes($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
           
    }
     function ingresorep()
    {
        if($this->acceso(140)){
            $data['usuario_nombre'] = $this->session_data['usuario_nombre'];
            $data['usuario_id'] = $this->session_data['usuario_id'];
            $this->load->model('Empresa_model');
            $data['all_empresa'] = $this->Empresa_model->get_all_empresa();
            /*
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            */
            $data['page_title'] = "Reportes";
            $data['_view'] = 'reportes/ingresorep';

            $this->load->view('layouts/main',$data);
        }
    }
    function reporteingreso()
    {
        if($this->acceso(140)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_ingresoreportes($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }
    /* reporte ingrso/egreso individual */
    function reportepersonal()
    {
        if($this->acceso(139)){
        $this->load->model('Empresa_model');
        $data['all_empresa'] = $this->Empresa_model->get_all_empresa();

        $data['usuario_nombre'] = $this->session_data['usuario_nombre'];
        $data['usuario_id'] = $this->session_data['usuario_id'];
        $data['page_title'] = "Reportes";
        $data['_view'] = 'reportes/reportepersonal';

        $this->load->view('layouts/main',$data);

        }

           

    }
    function buscarlosreportespersonal()
    {
        if($this->acceso(139)){
        if ($this->input->is_ajax_request()) {

            $fecha1 = $this->input->post('fecha1');   
            $fecha2 = $this->input->post('fecha2'); 
            $usuario = $this->input->post('usuario_id'); 
            $valfecha1 = "";
            $valfecha2 = "";
            $usuario_id = "";

            if(!($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha2;
            }elseif(!($fecha1 == null || empty($fecha1)) && ($fecha2 == null || empty($fecha2))){
                $valfecha1 = $fecha1;
                $valfecha2 = $fecha1;
            }elseif(($fecha1 == null || empty($fecha1)) && !($fecha2 == null || empty($fecha2))) {
                $valfecha1 = $fecha2;
                $valfecha2 = $fecha2;
            }else{
                $fecha1 = null;
                $fecha2 = null;
            }

            if($usuario >  0){
                $usuario_id = $usuario;
            }else{
                $usuario_id = 0;
            }
            
            $datos = $this->Reporte_ing_egr_model->get_reportes($valfecha1, $valfecha2, $usuario_id);
            echo json_encode($datos);
        }   
        else
        {                 
            show_404();
        }
        
        }
            
    }
    function ventacliente()
    {
        if($this->acceso(156)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $this->load->model('Tipo_transaccion_model');
            $data['page_title'] = "Reporte de Ventas por Cliente";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);  
            $data['all_tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion();
            $this->load->model('Usuario_model');
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'reportes/ventacliente';
            $this->load->view('layouts/main',$data);
        }
    }
    function ventaproducto()
    {
        if($this->acceso(156)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $this->load->model('Tipo_transaccion_model');
            $data['page_title'] = "Reporte de ventas por producto";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);  
            $data['all_tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion();
            $this->load->model('Usuario_model');
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            //$data['all_entrega'] = $this->Detalle_venta_model->get_all_entrega();
            $data['_view'] = 'reportes/ventaproducto';
            $this->load->view('layouts/main',$data);
        }
    }
    function ventapagrupado()
    {
        if($this->acceso(156)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $this->load->model('Tipo_transaccion_model');
            $data['page_title'] = "Reporte de ventas agrupado";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);  
            $data['all_tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion();
            $this->load->model('Usuario_model');
            $data['all_usuario'] = $this->Usuario_model->get_all_usuario_activo();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'reportes/ventapagrupado';
            $this->load->view('layouts/main',$data);
        }
    }
    /* reporte de ventas por categoria */
    function ventacategoria()
    {
        if($this->acceso(157)){
        $data['empresa'] = $this->Empresa_model->get_all_empresa();
        $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
        $this->load->model('Parametro_model');
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $this->load->model('Moneda_model');
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $data['page_title'] = "Reporte de ventas por categorias";
        $this->load->model('Categoria_producto_model');
        $data['all_categoria'] = $this->Categoria_producto_model->get_all_categoria_producto();
        $data['_view'] = 'reportes/ventacategoria';

        $this->load->view('layouts/main',$data);
        }
    }
    /* reporte de ventas por ruta(zonas) */
    function ventaruta()
    {
        if($this->acceso(157)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $data['empresa'] = $this->Empresa_model->get_all_empresa();
            $this->load->model('Categoria_clientezona_model');
            $data['all_zona'] = $this->Categoria_clientezona_model->get_all_categoria_clientezona();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['page_title'] = "Reporte por Rutas o Zonas";
            $data['_view'] = 'reportes/ventaruta';

            $this->load->view('layouts/main',$data);
        }
    }
    /* reporte de ventas por usuario */
    function ventausuario()
    {
        if($this->acceso(157)){
        $data['empresa'] = $this->Empresa_model->get_all_empresa();
        $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
        $this->load->model('Parametro_model');
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $this->load->model('Moneda_model');
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $data['page_title'] = "Reporte de ventas por usuario";
        $data['_view'] = 'reportes/ventausuario';

        $this->load->view('layouts/main',$data);
        }
    }
    
    
    function repventa_categoria()
    {
        $fecha_desde = $this->input->post('fecha_desde');
        $fecha_hasta = $this->input->post('fecha_hasta');
        
        $this->load->model('Categoria_producto_model');
        $res_categoria = $this->Categoria_producto_model->get_all_categoria_ventaproducto_count($fecha_desde, $fecha_hasta);
        $numusu = count($res_categoria);
        
        /*$ventausuario = "SELECT COUNT(DISTINCT cliente_id) as 'distusu',SUM(venta_total) as 'totalventas' FROM venta where venta.venta_fecha >= '".$anio."-".$mes."-01' and  venta.venta_fecha <= '".$anio."-".$mes."-31' ORDER by totalventas limit 10";
        $usve = $this->db->query($ventausuario)->row_array();
        $numusu=10;*/

        $usuarios = $this->Categoria_producto_model->getall_ventapor_categoria($fecha_desde, $fecha_hasta);
        
        /*$id_usuarios = "SELECT DISTINCT v.cliente_id, u.cliente_nombre,SUM(venta_total) as 'totalventas' FROM venta v, cliente u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and v.cliente_id=u.cliente_id GROUP BY cliente_id ORDER by totalventas desc limit 10";
        $usuarios= $this->db->query($id_usuarios)->result_array();
        */
        
        $tove = $usuarios;
        /*$totalventas = "SELECT DISTINCT v.cliente_id, SUM(venta_total) as 'totalventas' FROM venta v, cliente u where v.venta_fecha >= '".$anio."-".$mes."-01' and  v.venta_fecha <= '".$anio."-".$mes."-31' and v.cliente_id=u.cliente_id GROUP BY cliente_id ORDER by totalventas desc limit 10";
        $tove= $this->db->query($totalventas)->result_array();
        */
        
        
        foreach($usuarios as $tve){
        $ususel=intval($tve['categoria_id']);
        
        $suma=round($tve['totalventas'],2);
        
        $registros[$ususel]=$suma;    
        }
        //var_dump($numusu);
        $data=array("totaltipos"=>$numusu, "tipos" =>$usuarios, "numerodepubli" =>$registros);
        echo   json_encode($data);
    }
    /* reporte de ventas por zonas */
    function repventa_zonas()
    {
        $fecha_desde = $this->input->post('fecha_desde');
        $fecha_hasta = $this->input->post('fecha_hasta');
        
        $this->load->model('Categoria_clientezona_model');
        $res_zona = $this->Categoria_clientezona_model->get_all_zonas_ventaproducto_count($fecha_desde, $fecha_hasta);
        $numusu = count($res_zona);
        
        $usuarios = $this->Categoria_clientezona_model->getall_ventapor_zonas($fecha_desde, $fecha_hasta);
        
        $tove = $usuarios;
        
        foreach($usuarios as $tve){
        $ususel=intval($tve['zona_id']);
        
        $suma=round($tve['totalventas'],2);
        
        $registros[$ususel]=$suma;    
        }
        //var_dump($numusu);
        $data=array("totaltipos"=>$numusu, "tipos" =>$usuarios, "numerodepubli" =>$registros);
        echo   json_encode($data);   
    }
    /* reporte de ventas por usuario */
    function repventa_usuario()
    {
        $fecha_desde = $this->input->post('fecha_desde');
        $fecha_hasta = $this->input->post('fecha_hasta');
        
        $this->load->model('Categoria_producto_model');
        $res_usuario = $this->Categoria_producto_model->get_all_usuario_ventaproducto_count($fecha_desde, $fecha_hasta);
        $numusu = count($res_usuario);
        
        $usuarios = $this->Categoria_producto_model->getall_ventapor_usuario($fecha_desde, $fecha_hasta);
        $tove = $usuarios;
        
        foreach($usuarios as $tve){
            $ususel=intval($tve['usuario_id']);
            $suma=round($tve['totalventas'],2);
            $registros[$ususel]=$suma;
        }
        //var_dump($numusu);
        $data=array("totaltipos"=>$numusu, "tipos" =>$usuarios, "numerodepubli" =>$registros);
        echo   json_encode($data);   
    }
    
    function venta()
    {
        if($this->acceso(141)){
        
        $data['page_title'] = "Reporte de ventas";
        $data['_view'] = 'reportes/indexventa';

        $this->load->view('layouts/main',$data);
        }
    }
    function reporte_generalventa()
    {
        $data['empresa'] = $this->Empresa_model->get_empresa(1);
        $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
        $this->load->model('Tipo_transaccion_model');
        $data['all_tipo_transaccion'] = $this->Tipo_transaccion_model->get_all_tipo_transaccion();
        $this->load->model('Parametro_model');
        $elparametro = $this->Parametro_model->get_parametros();
        $data['parametro'] = $this->Parametro_model->get_parametros();
        $this->load->model('Moneda_model');
        $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
        $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
        $data['elparametro'] = $elparametro;
        $data['page_title'] = "Reporte general - Ventas a Clientes";
        $data['_view'] = 'reportes/reporte_generalventa';
        $this->load->view('layouts/main',$data);
    }
    /* busca ventas por cliente en un rango de fachas */
    function busqueda_venta()
    {
        if ($this->input->is_ajax_request()) {
            $fecha_desde = $this->input->post('fecha_desde');
            $fecha_hasta = $this->input->post('fecha_hasta');

            $datos = $this->Reporte_ing_egr_model->getall_ventaagrupado_porcliente($fecha_desde, $fecha_hasta);
            echo json_encode($datos);
        }else{
            show_404();
        }
    }
    function ventacategoria_pagrupado()
    {
        if($this->acceso(156)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $data['page_title'] = "Reporte de ventas de productos agrupados por categorias";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);  
            $this->load->model('Categoria_producto_model');
            $data['all_categoria'] = $this->Categoria_producto_model->get_all_categoria_producto();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            $this->load->model('Moneda_model');
            $data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            $data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'reportes/ventacategoria_pagrupado';
            $this->load->view('layouts/main',$data);
        }
    }
    function ventacategoriap()
    {
        //if($this->acceso(156)){
            $data['tipousuario_id'] = $this->session_data['tipousuario_id'];
            $data['page_title'] = "Reporte de ventas de productos agrupados por categorias";
            $data['empresa'] = $this->Empresa_model->get_empresa(1);  
            //$this->load->model('Categoria_producto_model');
            //$data['all_categoria'] = $this->Categoria_producto_model->get_all_categoria_producto();
            $this->load->model('Parametro_model');
            $data['parametro'] = $this->Parametro_model->get_parametros();
            //$this->load->model('Moneda_model');
            //$data['moneda'] = $this->Moneda_model->get_moneda(2); //Obtener moneda extragera
            //$data['lamoneda'] = $this->Moneda_model->getalls_monedasact_asc();
            $data['_view'] = 'reportes/ventacategoriap';
            $this->load->view('layouts/main',$data);
        //}
    }
    /* reeporte de productos agrupados por categoria */
    function buscarprodagrupados_porcategoria()
    {
        if ($this->input->is_ajax_request()) {
            $filtro = $this->input->post('filtro');
            $datos = $this->Reporte_ing_egr_model->reporteventas_prodagrupados($filtro);
            echo json_encode($datos);
        }else{
            show_404();
        }
    }
    
    /*
    * muestra las sesiones de un paciente
    */
    public function losreportes()
    {
        if($this->acceso(49)){
            try{
                $data['_view'] = 'reportes/losreportes';
                $this->load->view('layouts/main',$data);
            } catch (Exception $ex) {
                throw new Exception('Reporte Controller : Error in index function - ' . $ex);
            }
        }
    }
    
}
