<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Sesion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sesion_model');
    }
    
    /*
    * Listing of sesion
    */
    public function index()
    {
        $data['_view'] = 'sesion/index';
        $this->load->view('layouts/main',$data);
    }
    
    
    
    
    /*
    * Listing of sesion
    */
    /*public function index()
    {
        try{
          $data['noof_page'] = 0;
         $data['sesion'] = $this->Sesion_model->get_all_sesion();
          $data['_view'] = 'sesion/index';
          $this->load->view('layouts/main',$data);
        } catch (Exception $ex) {
        throw new Exception('Sesion Controller : Error in index function - ' . $ex);
      }  
    }*/
     /*
      * Adding a new sesion
      */
     function add()
     {  
    try{
          $params = array(
           'usuario_id'=> $this->input->post('usuario_id'),
           'paciente_id'=> $this->input->post('paciente_id'),
           'sesion_fecha'=> $this->input->post('sesion_fecha'),
           'sesion_hora'=> $this->input->post('sesion_hora'),
           'sesion_mes'=> $this->input->post('sesion_mes'),
           'sesion_gestion'=> $this->input->post('sesion_gestion'),
           'sesion_diagnostico'=> $this->input->post('sesion_diagnostico'),
            );
           $this->load->library('upload');
           $this->load->library('form_validation');
           if(isset($_POST) && count($_POST) > 0)     
            {  
                $sesion_id= $this->Sesion_model->add_sesion($params);
                 $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
                  redirect('sesion/index');
            }
            else
            { 
               $data['_view'] = 'sesion/add';
                $this->load->view('layouts/main',$data);
            }
      } catch (Exception $ex) {
        throw new Exception('Sesion Controller : Error in add function - ' . $ex);
      }  
     }  
      /*
      * Editing a sesion
     */
     public function edit($sesion_id)
     {   
      try{
       $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
           $this->load->library('upload');
           $this->load->library('form_validation');
         if(isset($data['sesion']['sesion_id']))
          {
            $params = array(
               'usuario_id'=> $this->input->post('usuario_id'),
               'paciente_id'=> $this->input->post('paciente_id'),
               'sesion_fecha'=> $this->input->post('sesion_fecha'),
               'sesion_hora'=> $this->input->post('sesion_hora'),
               'sesion_mes'=> $this->input->post('sesion_mes'),
               'sesion_gestion'=> $this->input->post('sesion_gestion'),
               'sesion_diagnostico'=> $this->input->post('sesion_diagnostico'),
            );
              if(isset($_POST) && count($_POST) > 0)     
               {  
               $this->Sesion_model->update_sesion($sesion_id,$params);
                 $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                    redirect('sesion/index');
               }
               else
              {
                  $data['_view'] = 'sesion/edit';
                  $this->load->view('layouts/main',$data);
              }
      }
      else
      show_error('The sesion you are trying to edit does not exist.');
      } catch (Exception $ex) {
        throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
      }  
    } 
    /*
      * Deleting sesion
      */
      function remove($sesion_id)
       {
        try{
          $sesion = $this->Sesion_model->get_sesion($sesion_id);
      // check if the sesion exists before trying to delete it
           if(isset($sesion['sesion_id']))
           {
             $this->Sesion_model->delete_sesion($sesion_id);
                 $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
               redirect('sesion/index');
           }
           else
           show_error('The sesion you are trying to delete does not exist.');
      } catch (Exception $ex) {
        throw new Exception('Sesion Controller : Error in remove function - ' . $ex);
      }  
      }
 }
