<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Sesion extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sesion_model');
        $this->load->model('Registro_model');
        $this->load->model('Tratamiento_model');
        $this->load->model('Acceso_vascular_model');
        $this->load->model('Medicacion_model');
        $this->load->model('Medicamento_model');
        $this->load->model('Estado_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
    * Listing of sesion
    */
    /*public function index()
    {
        $data['_view'] = 'sesion/index';
        $this->load->view('layouts/main',$data);
    }*/
    
    /*
    * Listing of sesiones de un tratamiento
    */
    public function sesiones($tratamiento = 0)
    {
        if($this->acceso(23)){
            $data["rol"] = $this->session_data['rol'];
            $data['tratamiento_id'] = $tratamiento;
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($tratamiento);
            /*$sesion = $this->Sesion_model->get_all_sesion();
            $data['hay_sesiones']  = 0;
            if(count($sesion)>0){
                $data['hay_sesiones']  = 1;
            }*/
            $data['_view'] = 'sesion/sesiones';
            $this->load->view('layouts/main',$data);
        }
    }
    
    function mostrar_sesiones(){
        try{
            if($this->input->is_ajax_request()){
                $tratamiento_id = $this->input->post('tratamiento_id');
                $sesion = $this->Sesion_model->get_all_sesiontratamiento($tratamiento_id);
                echo json_encode($sesion);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function generar_sesion(){
        try{
            if($this->input->is_ajax_request()){
                $sesion_numero = $this->input->post('sesion_numero');
                $sesion_fechainicio = $this->input->post('sesion_fechainicio');
                // 0=>Domingo, 1=>Lunes, 2=>Martes, 3=>Miercoles, 4=>Jueves, 5=>Viernes, 6=>Sabado
                $dia = date("w", strtotime($sesion_fechainicio));
                if($dia >0){
                    $tratamiento_id = $this->input->post('tratamiento_id');
                    $registro = $this->Registro_model->get_registro_detratamiento($tratamiento_id);
                    $numero_registro = $registro["registro_numerosesion"];
                    $registro_numaquina = $registro["registro_numaquina"];
                    $registro_tipofiltro = $registro["registro_tipofiltro"];
                    $registro_filtro     = $registro["registro_filtro"];
                    $acceso_vascular = $this->Acceso_vascular_model->get_ultimoa_vascularregistro($registro["registro_id"]);
                    $cateter = "";
                    $fistula = "";
                    if($acceso_vascular["avascular_nombre"] == "Cateter"){
                        $cateter = $acceso_vascular["avascular_detalle"];
                        
                    }else{
                        $fistula = $acceso_vascular["avascular_detalle"];
                    }
                    $lmv = 0;  //0==>false;  1==>true
                    if($dia == 1 || $dia == 3 || $dia == 5){
                        $lmv = 1;
                    }
                    $estado_id = 3; // estado pendiente
                    $num_filtro = 0;
                    $filtro_usado = "";
                    $cont = 1;
                    for($i = 1; $i <= $sesion_numero; $i++){
                        $num_reg    = ($numero_registro+$i);
                        $num_filtro = ($registro_filtro+$cont);
                        $cont++;
                        if($num_filtro >= 12){
                            $registro_filtro = 0;
                            $cont = 1;
                            if($num_filtro > 12){
                                $num_filtro = 1;
                                $cont = 2;
                            }
                        }
                        
                        $params = array(
                            'tratamiento_id' => $this->input->post('tratamiento_id'),
                            'sesion_numero' => $i,
                            'sesion_fecha' => $sesion_fechainicio,
                            'sesion_eritropoyetina' => $this->input->post('sesion_eritropoyetina'),
                            'sesion_hierroeve' => $this->input->post('sesion_hierroev'),
                            'sesion_complejobampolla' => $this->input->post('sesion_complejobampolla'),
                            'sesion_costosesion' => $this->input->post('sesion_costosesion'),
                            'sesion_nummaquina' => $registro_numaquina,
                            'sesion_tipofiltro' => $registro_tipofiltro,
                            'sesion_cateter' => $cateter,
                            'sesion_fistula' => $fistula,
                            'sesion_numerosesionhd' => $num_reg,
                            'estado_id' => $estado_id,
                            'avascular_id' => $acceso_vascular["avascular_id"],
                            'sesion_reutlizacionfiltro' => $num_filtro,
                            'sesion_lineasav' => $num_filtro,
                            'sesion_devolucion' => 300,
                            'sesion_heparina' => 5000,
                        );
                        $sesion_id = $this->Sesion_model->add_sesion($params);
                        
                        if($this->input->post('sesion_eritropoyetina') > 0){
                            $params = array(
                               'sesion_id'=> $sesion_id,
                               'medicamento_id'=> 21, // Jeringa descartable1 ml. c./aguja
                               'estado_id'=> 1,
                               'medicacion_cantidad'=> 1,
                                );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }

                        $dia = date("w", strtotime($sesion_fechainicio));

                        if($lmv == 1){
                            if($dia == 1 || $dia == 3){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+2 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 2,
                                    'sesion_acidofolico' => 2,
                                    'sesion_calcio' => 4,
                                    //'sesion_amlodipina' => 4,
                                    'sesion_complejob' => 2,
                                );
                            }elseif($dia == 5){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+3 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 3,
                                    'sesion_acidofolico' => 3,
                                    'sesion_calcio' => 6,
                                    //'sesion_amlodipina' => 6,
                                    'sesion_complejob' => 3,
                                );
                            }
                        }else{
                            if($dia == 2 || $dia == 4){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+2 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 2,
                                    'sesion_acidofolico' => 2,
                                    'sesion_calcio' => 4,
                                    //'sesion_amlodipina' => 4,
                                    'sesion_complejob' => 2,
                                );
                            }elseif($dia == 6){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+3 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 3,
                                    'sesion_acidofolico' => 3,
                                    'sesion_calcio' => 6,
                                    //'sesion_amlodipina' => 6,
                                    'sesion_complejob' => 3,
                                );
                            }
                        }
                        $this->Sesion_model->update_sesion($sesion_id, $paramsok);
                        
                        if($num_filtro == 1){
                            $medicamento_id = 28; // "FILTRO HPS F8/DIACAP/ELISIO 21 H"
                            $cantidad = 1; // es uno porque es al regla del negocio
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> $medicamento_id,
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> $cantidad,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }
                        
                        if($acceso_vascular["avascular_nombre"] == "Cateter"){
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 3, // barbijo descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 4, // Batas descartables
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 8, // Equipo de venoclisis c/aguja Nº 21 G 1 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 10, // Gorro descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 11, // Guantes quirúrgicos descartables Nº 7 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 12, // Guantes descartables Nº 7
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 4,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 13, // Heparina sódica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 17, // Jeringa descartable 20 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 3,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 18, // Jeringa descartable 10 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 19, // Jeringa descartable 5 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 20, // Jeringa descartable3 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 22, // Lineas A-V
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 23, // Solucion Acida
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 24, // Solución Básica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 25, // Solución Fisiologica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            if(($i%2) != 0){
                                $params = array(
                                    'sesion_id'=> $sesion_id,
                                    'medicamento_id'=> 26, // Tela adhesiva micropore 2.5  x 10 m.
                                    'estado_id'=> 1,
                                    'medicacion_cantidad'=> 1,
                                );
                                $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            }
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 27, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 29, // STOPPER IN
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 30, // OTROS INSUMOS CATETER
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }else{
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 2, // Aguja p/fistula arterio-venosa (Par)
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 3, // Barbijo descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 8, // Equipo de venoclisis c/aguja Nº 21 G 1 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 10, // Gorro descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 12, // Guantes descartables Nº 7
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 4,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 13, // Heparina sódica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 17, // Jeringa descartable 20 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 3,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 19, // Jeringa descartable 5 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 22, // Lineas A-V
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 23, // Solucion Acida
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 24, // Solución Básica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 25, // Solución Fisiologica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            if(($i%2) != 0){
                                $params = array(
                                    'sesion_id'=> $sesion_id,
                                    'medicamento_id'=> 26, // Tela adhesiva micropore 2.5  x 10 m.
                                    'estado_id'=> 1,
                                    'medicacion_cantidad'=> 1,
                                );
                                $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            }
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 27, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 31, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }
                        
                    }
                    $params = array(
                        'registro_numerosesion' => $num_reg,
                    );
                    $this->Registro_model->update_registro($registro["registro_id"], $params);
                    
                    $params = array(
                        'registro_filtro' => $num_filtro,
                    );
                    $this->Registro_model->update_registro($registro["registro_id"], $params);
                    
                    echo json_encode("ok");
                }else{
                    echo json_encode("no");
                }
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
    * modificar una sesión
    */
    public function modificar($sesion_id)
    {
        if($this->acceso(25)){
            try{
                //$data['tratamiento_id'] = $tratamiento_id;
                $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
                $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($data['sesion']['tratamiento_id']);
                $tipo = 2;
                $data['all_estado'] = $this->Estado_model->get_estado_tipo($tipo);

                $this->load->library('upload');
                $this->load->library('form_validation');
                if(isset($data['sesion']['sesion_id']))
                {
                    if(isset($_POST) && count($_POST) > 0)     
                    {
                        $params = array(
                            'sesion_eritropoyetina'=> $this->input->post('sesion_eritropoyetina'),
                            'sesion_hierroeve'=> $this->input->post('sesion_hierroeve'),
                            'sesion_complejobampolla'=> $this->input->post('sesion_complejobampolla'),
                            'sesion_costosesion'=> $this->input->post('sesion_costosesion'),
                            'sesion_omeprazol'=> $this->input->post('sesion_omeprazol'),
                            'sesion_acidofolico'=> $this->input->post('sesion_acidofolico'),
                            'sesion_calcio'=> $this->input->post('sesion_calcio'),
                            'sesion_amlodipina'=> $this->input->post('sesion_amlodipina'),
                            'sesion_enalpril'=> $this->input->post('sesion_enalpril'),
                            'sesion_losartan'=> $this->input->post('sesion_losartan'),
                            'sesion_atorvastina'=> $this->input->post('sesion_atorvastina'),
                            'sesion_asa'=> $this->input->post('sesion_asa'),
                            'sesion_complejob'=> $this->input->post('sesion_complejob'),
                            'estado_id'=> $this->input->post('estado_id'),
                        );
                        $this->Sesion_model->update_sesion($sesion_id,$params);

                        $medicamento_id = 21; // Jeringa descartable1 ml. c./aguja
                        $lamedicacion = $this->Medicacion_model->get_medicamento_sesion($sesion_id, $medicamento_id);
                        if($this->input->post('sesion_eritropoyetina') > 0){
                            if(isset($lamedicacion)){
                                $params = array(
                                    'medicacion_cantidad'=> $this->input->post('sesion_eritropoyetina'),
                                    'estado_id'=> 1,
                                );
                                $this->Medicacion_model->update_medicacion($lamedicacion["medicacion_id"], $params);
                            }else{
                                $params = array(
                                    'sesion_id'=> $sesion_id,
                                    'medicamento_id'=> 21, // Jeringa descartable1 ml. c./aguja
                                    'estado_id'=> 1,
                                    'medicacion_cantidad'=> $this->input->post('sesion_eritropoyetina'),
                                );
                                $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            }
                        }else{
                            if(isset($lamedicacion)){
                                $params = array(
                                    'estado_id'=> 2,
                                );
                                $this->Medicacion_model->update_medicacion($lamedicacion["medicacion_id"], $params);
                            }
                        }


                        $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Información modificada con exito</div>');
                        redirect('sesion/sesiones/'.$data['sesion']['tratamiento_id']);
                    }else{
                        $data['_view'] = 'sesion/modificar';
                        $this->load->view('layouts/main',$data);
                    }
                }else
                    show_error('La sesion que intentas modifcar no existe!.');
            }catch (Exception $ex) {
                throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
            }
        }
    }
    
    /*
    * modificar una sesión
    */
    public function detalle_procedimiento($sesion_id)
    {
        if($this->acceso(26)){
            try{
                //$data['tratamiento_id'] = $tratamiento_id;
                $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
                $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($data['sesion']['tratamiento_id']);
                /*$tipo = 1;
                $data['all_estado'] = $this->Estado_model->get_estado_tipo($tipo);
                */
                $this->load->library('upload');
                $this->load->library('form_validation');
                if(isset($data['sesion']['sesion_id']))
                {
                    if(isset($_POST) && count($_POST) > 0)     
                    {
                        $params = array(
                            'sesion_horaingreso'=> $this->input->post('sesion_horaingreso'),
                            'sesion_horasalida'=> $this->input->post('sesion_horasalida'),
                            'sesion_numerosesionhd'=> $this->input->post('sesion_numerosesionhd'),
                            'sesion_fecha'=> $this->input->post('sesion_fecha'),
                            'sesion_paingreso'=> $this->input->post('sesion_paingreso'),
                            'sesion_ingest'=> $this->input->post('sesion_ingest'),
                            'sesion_pesoseco'=> $this->input->post('sesion_pesoseco'),
                            'sesion_pesoingreso'=> $this->input->post('sesion_pesoingreso'),
                            'sesion_pesoegreso'=> $this->input->post('sesion_pesoegreso'),
                            'sesion_nummaquina'=> $this->input->post('sesion_nummaquina'),
                            'sesion_ultrafilsesion'=> $this->input->post('sesion_ultrafilsesion'),
                            'sesion_ultrafilfinal'=> $this->input->post('sesion_ultrafilfinal'),
                            'sesion_tipofiltro'=> $this->input->post('sesion_tipofiltro'),
                            'sesion_reutlizacionfiltro'=> $this->input->post('sesion_reutlizacionfiltro'),
                            'sesion_lineasav'=> $this->input->post('sesion_lineasav'),
                            'sesion_devolucion'=> $this->input->post('sesion_devolucion'),
                            'sesion_heparina'=> $this->input->post('sesion_heparina'),
                            'sesion_ktv'=> $this->input->post('sesion_ktv'),
                            'sesion_evaluacionenfermeria'=> $this->input->post('sesion_evaluacionenfermeria'),
                            'sesion_cateter'=> $this->input->post('sesion_cateter'),
                            'sesion_fistula'=> $this->input->post('sesion_fistula'),
                            'sesion_evaluacionclinica'=> $this->input->post('sesion_evaluacionclinica'),
                            'sesion_tratamiento'=> $this->input->post('sesion_tratamiento'),
                            'sesion_medicamentosextra'=> $this->input->post('sesion_medicamentosextra'),
                        );
                        $this->Sesion_model->update_sesion($sesion_id,$params);
                        $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Información modificada con exito</div>');
                        redirect('sesion/sesiones/'.$data['sesion']['tratamiento_id']);
                    }else{
                        $data["rol"] = $this->session_data['rol'];
                        $data['_view'] = 'sesion/detalle_procedimiento';
                        $this->load->view('layouts/main',$data);
                    }
                }else
                    show_error('La sesion que intentas modifcar no existe!.');
            }catch (Exception $ex) {
                throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
            }
        }
    }
    
    /*
    * Listing of sesiones de un tratamiento
    */
    public function detalle_medicacion($sesion_id = 0)
    {
        if($this->acceso(32)){
            $data["rol"] = $this->session_data['rol'];
            $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
            $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($data['sesion']["tratamiento_id"]);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($data['sesion']["tratamiento_id"]);
            $data['medicamentos'] = $this->Medicamento_model->get_all_medicamento();

            $data['_view'] = 'sesion/detalle_medicacion';
            $this->load->view('layouts/main',$data);
        }
    }
    /* muestra medicamentos usados  en una determinada sesion */
    function mostrar_medicamentos(){
        try{
            if($this->input->is_ajax_request()){
                $sesion_id = $this->input->post('sesion_id');
                $medicamento = $this->Medicacion_model->getall_medicamentosusados($sesion_id);
                echo json_encode($medicamento);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
    * muestra las sesiones de un paciente
    */
    public function lassesiones()
    {
        if($this->acceso(47)){
            try{
                $data['_view'] = 'sesion/lassesiones';
                $this->load->view('layouts/main',$data);
            } catch (Exception $ex) {
                throw new Exception('Sesion Controller : Error in index function - ' . $ex);
            }
        }
    }
    
    function mostrar_sesiones_aregistrar(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $sesion = $this->Sesion_model->getall_sesionallenar_paciente($paciente_id);
                echo json_encode($sesion);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
    * modificar una sesión por enfermeras y doctoras
     * usa del panel registro detalle de sesiones y registro sesiones
    */
    public function detalle_procedimientoed($sesion_id)
    {
        try{
            //$data['tratamiento_id'] = $tratamiento_id;
            $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($data['sesion']['tratamiento_id']);
            /*$tipo = 1;
            $data['all_estado'] = $this->Estado_model->get_estado_tipo($tipo);
            */
            $this->load->library('upload');
            $this->load->library('form_validation');
            if(isset($data['sesion']['sesion_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {
                    $params = array(
                        'sesion_horaingreso'=> $this->input->post('sesion_horaingreso'),
                        'sesion_horasalida'=> $this->input->post('sesion_horasalida'),
                        'sesion_numerosesionhd'=> $this->input->post('sesion_numerosesionhd'),
                        'sesion_fecha'=> $this->input->post('sesion_fecha'),
                        'sesion_paingreso'=> $this->input->post('sesion_paingreso'),
                        'sesion_ingest'=> $this->input->post('sesion_ingest'),
                        'sesion_pesoseco'=> $this->input->post('sesion_pesoseco'),
                        'sesion_pesoingreso'=> $this->input->post('sesion_pesoingreso'),
                        'sesion_pesoegreso'=> $this->input->post('sesion_pesoegreso'),
                        'sesion_nummaquina'=> $this->input->post('sesion_nummaquina'),
                        'sesion_ultrafilsesion'=> $this->input->post('sesion_ultrafilsesion'),
                        'sesion_ultrafilfinal'=> $this->input->post('sesion_ultrafilfinal'),
                        'sesion_tipofiltro'=> $this->input->post('sesion_tipofiltro'),
                        'sesion_reutlizacionfiltro'=> $this->input->post('sesion_reutlizacionfiltro'),
                        'sesion_lineasav'=> $this->input->post('sesion_lineasav'),
                        'sesion_devolucion'=> $this->input->post('sesion_devolucion'),
                        'sesion_heparina'=> $this->input->post('sesion_heparina'),
                        'sesion_ktv'=> $this->input->post('sesion_ktv'),
                        'sesion_evaluacionenfermeria'=> $this->input->post('sesion_evaluacionenfermeria'),
                        'sesion_cateter'=> $this->input->post('sesion_cateter'),
                        'sesion_fistula'=> $this->input->post('sesion_fistula'),
                        'sesion_evaluacionclinica'=> $this->input->post('sesion_evaluacionclinica'),
                        'sesion_tratamiento'=> $this->input->post('sesion_tratamiento'),
                        'sesion_medicamentosextra'=> $this->input->post('sesion_medicamentosextra'),
                    );
                    $this->Sesion_model->update_sesion($sesion_id,$params);
                    $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Información modificada con exito</div>');
                    redirect('sesion/lassesiones');
                }else{
                    $data['_view'] = 'sesion/detalle_procedimientoed';
                    $this->load->view('layouts/main',$data);
                }
            }else
                show_error('La sesion que intentas modifcar no existe!.');
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    /*
    * muestra las sesiones de un paciente
    */
    public function lassesionesmodif()
    {
        if($this->acceso(48)){
            try{
                $data['_view'] = 'sesion/lassesionesmodif';
                $this->load->view('layouts/main',$data);
            } catch (Exception $ex) {
                throw new Exception('Sesion Controller : Error in index function - ' . $ex);
            }
        }
    }
    /*
    * modificar una sesión desde dashboard
    */
    public function modificarmodif($sesion_id)
    {
        try{
            //$data['tratamiento_id'] = $tratamiento_id;
            $data['sesion'] = $this->Sesion_model->get_sesion($sesion_id);
            $data['paciente'] = $this->Sesion_model->get_pacientetratamiento($data['sesion']['tratamiento_id']);
            $tipo = 2;
            $data['all_estado'] = $this->Estado_model->get_estado_tipo($tipo);
            
            $this->load->library('upload');
            $this->load->library('form_validation');
            if(isset($data['sesion']['sesion_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {
                    $params = array(
                        'sesion_eritropoyetina'=> $this->input->post('sesion_eritropoyetina'),
                        'sesion_hierroeve'=> $this->input->post('sesion_hierroeve'),
                        'sesion_complejobampolla'=> $this->input->post('sesion_complejobampolla'),
                        'sesion_costosesion'=> $this->input->post('sesion_costosesion'),
                        'sesion_omeprazol'=> $this->input->post('sesion_omeprazol'),
                        'sesion_acidofolico'=> $this->input->post('sesion_acidofolico'),
                        'sesion_calcio'=> $this->input->post('sesion_calcio'),
                        'sesion_amlodipina'=> $this->input->post('sesion_amlodipina'),
                        'sesion_enalpril'=> $this->input->post('sesion_enalpril'),
                        'sesion_losartan'=> $this->input->post('sesion_losartan'),
                        'sesion_atorvastina'=> $this->input->post('sesion_atorvastina'),
                        'sesion_asa'=> $this->input->post('sesion_asa'),
                        'sesion_complejob'=> $this->input->post('sesion_complejob'),
                        'estado_id'=> $this->input->post('estado_id'),
                    );
                    $this->Sesion_model->update_sesion($sesion_id,$params);
                    
                    $medicamento_id = 21; // Jeringa descartable1 ml. c./aguja
                    $lamedicacion = $this->Medicacion_model->get_medicamento_sesion($sesion_id, $medicamento_id);
                    if($this->input->post('sesion_eritropoyetina') > 0){
                        if(isset($lamedicacion)){
                            $params = array(
                                'medicacion_cantidad'=> $this->input->post('sesion_eritropoyetina'),
                                'estado_id'=> 1,
                            );
                            $this->Medicacion_model->update_medicacion($lamedicacion["medicacion_id"], $params);
                        }else{
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 21, // Jeringa descartable1 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> $this->input->post('sesion_eritropoyetina'),
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }
                    }else{
                        if(isset($lamedicacion)){
                            $params = array(
                                'estado_id'=> 2,
                            );
                            $this->Medicacion_model->update_medicacion($lamedicacion["medicacion_id"], $params);
                        }
                    }
                    
                    
                    $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Información modificada con exito</div>');
                    redirect('sesion/lassesionesmodif/');
                }else{
                    $data['_view'] = 'sesion/modificarmodif';
                    $this->load->view('layouts/main',$data);
                }
            }else
                show_error('La sesion que intentas modifcar no existe!.');
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    /* es para reportes desde dashboard */
    function mostrar_sesionesde_paciente(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $sesion = $this->Sesion_model->getall_sesion_paciente($paciente_id);
                echo json_encode($sesion);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
     * Deleting sesion
     */
    function remove($sesion_id)
    {
        $sesion = $this->Sesion_model->get_sesion($sesion_id);
        
        // check if the sesion exists before trying to delete it
        if(isset($sesion['sesion_id']))
        {
            $tratamiento_id = $sesion['tratamiento_id'];
            $this->Sesion_model->delete_sesion($sesion_id);
            redirect('sesion/sesiones/'.$tratamiento_id);
        }
        else
            show_error('La Sesion que intentas eliminar no existe!....');
    }
    
    public function reajustar_numerosesion()
    {
        try{
            if($this->input->is_ajax_request()){
                $sesnumero_hd = $this->input->post('sesnumero_hd');
                $registro_id = $this->input->post('registro_id');
                $sesion_id = $this->input->post('sesion_id');
                $las_sesiones = $this->Sesion_model->get_sesionesmayores_asesion($registro_id,$sesion_id);
                foreach ($las_sesiones as $sesion) {
                    $params = array(
                        'sesion_numerosesionhd'=> $sesnumero_hd,
                    );
                    $medicacion_id= $this->Sesion_model->update_sesion($sesion["sesion_id"],$params);
                    $sesnumero_hd++;
                }
                $paramsr = array(
                    'registro_numerosesion'=> ($sesnumero_hd-1),
                );
                $this->Registro_model->update_registro($registro_id,$paramsr);
                $lasesion = $this->Sesion_model->get_sesion($sesion_id);
                echo json_encode($lasesion["sesion_numerosesionhd"]);
            }else{                 
                show_404();
            }
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    
    public function cambiar_numeromaquina()
    {
        try{
            if($this->input->is_ajax_request()){
                $sesion_nummaquina = $this->input->post('sesion_nummaquina');
                $registro_id = $this->input->post('registro_id');
                $sesion_id = $this->input->post('sesion_id');
                $uno_omas = $this->input->post('uno_omas');
                // si uno_omas es 1, entonces solo cambia en esa sesion,
                // caso contrario cambia en todas las sesiones posteriores
                if($uno_omas == 1){
                    $params = array(
                        'sesion_nummaquina'=> $sesion_nummaquina,
                    );
                    $this->Sesion_model->update_sesion($sesion_id,$params);
                }else{
                    $las_sesiones = $this->Sesion_model->get_sesionesmayores_asesion($registro_id,$sesion_id);
                    foreach ($las_sesiones as $sesion){
                        $params = array(
                            'sesion_nummaquina'=> $sesion_nummaquina,
                        );
                        $this->Sesion_model->update_sesion($sesion["sesion_id"],$params);
                    }
                    $paramsr = array(
                        'registro_numaquina'=> $sesion_nummaquina,
                    );
                    $this->Registro_model->update_registro($registro_id,$paramsr);
                }
                
                $lasesion = $this->Sesion_model->get_sesion($sesion_id);
                echo json_encode($lasesion["sesion_nummaquina"]);
            }else{                 
                show_404();
            }
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    
    public function cambiar_reutfiltro()
    {
        try{
            if($this->input->is_ajax_request()){
                $sesion_reutlizacionfiltro = $this->input->post('sesion_reutlizacionfiltro');
                $registro_id = $this->input->post('registro_id');
                $sesion_id = $this->input->post('sesion_id');
                
                $las_sesiones = $this->Sesion_model->get_sesionesmayores_asesion($registro_id,$sesion_id);
                /* elimina el medicamento 28-->FILTRO HPS F8/DIACAP/ELISIO 21 H */
                $medicamento_id = 28;
                foreach ($las_sesiones as $sesion){
                    $resultado  = $this->Medicacion_model->delete_medicacionsesion($sesion["sesion_id"], $medicamento_id);
                }
                $registro_filtro = ($sesion_reutlizacionfiltro-1);
                $num_filtro = 0;
                $cont = 1;
                foreach ($las_sesiones as $sesion){
                    $num_filtro = ($registro_filtro+$cont);
                    $cont++;
                    if($num_filtro >= 12){
                        $registro_filtro = 0;
                        $cont = 1;
                        if($num_filtro > 12){
                            $num_filtro = 1;
                            $cont = 2;
                        }
                    }
                    
                    $params = array(
                        'sesion_reutlizacionfiltro'=> $num_filtro,
                        'sesion_lineasav'=> $num_filtro,
                    );
                    $this->Sesion_model->update_sesion($sesion["sesion_id"],$params);
                    
                    if($num_filtro == 1){
                        $medicamento_id = 28; // "FILTRO HPS F8/DIACAP/ELISIO 21 H"
                        $cantidad = 1; // es uno porque es al regla del negocio
                        $params = array(
                            'sesion_id'=> $sesion["sesion_id"],
                            'medicamento_id'=> $medicamento_id,
                            'estado_id'=> 1,
                            'medicacion_cantidad'=> $cantidad,
                        );
                        $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                    }
                }
                
                $paramsr = array(
                    'registro_filtro'=> $num_filtro,
                );
                $this->Registro_model->update_registro($registro_id,$paramsr);
                
                $lasesion = $this->Sesion_model->get_sesion($sesion_id);
                echo json_encode($lasesion["sesion_reutlizacionfiltro"]);
            }else{                 
                show_404();
            }
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    
    public function cambiar_tipofiltro()
    {
        try{
            if($this->input->is_ajax_request()){
                $sesion_tipofiltro = $this->input->post('sesion_tipofiltro');
                $registro_id = $this->input->post('registro_id');
                $sesion_id = $this->input->post('sesion_id');
                
                $las_sesiones = $this->Sesion_model->get_sesionesmayores_asesion($registro_id,$sesion_id);
                foreach ($las_sesiones as $sesion){
                    $params = array(
                        'sesion_tipofiltro'=> $sesion_tipofiltro,
                    );
                    $this->Sesion_model->update_sesion($sesion["sesion_id"],$params);
                }
                $paramsr = array(
                    'registro_tipofiltro'=> $sesion_tipofiltro,
                );
                $this->Registro_model->update_registro($registro_id,$paramsr);
                
                $lasesion = $this->Sesion_model->get_sesion($sesion_id);
                echo json_encode($lasesion["sesion_tipofiltro"]);
            }else{                 
                show_404();
            }
        }catch (Exception $ex) {
            throw new Exception('Sesion Controller : Error in edit function - ' . $ex);
        }
    }
    
 }
