<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Tipo_procedimiento extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Tipo_procedimiento_model');
 } 
 /*
* Listing of tipo_procedimiento
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_all_tipo_procedimiento();
      $data['_view'] = 'tipo_procedimiento/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Tipo_procedimiento Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new tipo_procedimiento
  */
 function add()
 {  
try{
      $params = array(
       'paciente_id'=> $this->input->post('paciente_id'),
       'tipoproced_nombre'=> $this->input->post('tipoproced_nombre'),
       'tipoproced_descripcion'=> $this->input->post('tipoproced_descripcion'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $tipoproced_id= $this->Tipo_procedimiento_model->add_tipo_procedimiento($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('tipo_procedimiento/index');
        }
        else
        { 
           $data['_view'] = 'tipo_procedimiento/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Tipo_procedimiento Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a tipo_procedimiento
 */
 public function edit($tipoproced_id)
 {   
  try{
   $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['tipo_procedimiento']['tipoproced_id']))
      {
        $params = array(
           'paciente_id'=> $this->input->post('paciente_id'),
           'tipoproced_nombre'=> $this->input->post('tipoproced_nombre'),
           'tipoproced_descripcion'=> $this->input->post('tipoproced_descripcion'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Tipo_procedimiento_model->update_tipo_procedimiento($tipoproced_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('tipo_procedimiento/index');
           }
           else
          {
              $data['_view'] = 'tipo_procedimiento/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The tipo_procedimiento you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Tipo_procedimiento Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting tipo_procedimiento
  */
  function remove($tipoproced_id)
   {
    try{
      $tipo_procedimiento = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
  // check if the tipo_procedimiento exists before trying to delete it
       if(isset($tipo_procedimiento['tipoproced_id']))
       {
         $this->Tipo_procedimiento_model->delete_tipo_procedimiento($tipoproced_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('tipo_procedimiento/index');
       }
       else
       show_error('The tipo_procedimiento you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Tipo_procedimiento Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a tipo_procedimiento
 */
 public function view_more($tipoproced_id)
 {   
try{
   $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
     if(isset($data['tipo_procedimiento']['tipoproced_id']))
      {
              $data['_view'] = 'tipo_procedimiento/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The tipo_procedimiento you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Tipo_procedimiento Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of tipo_procedimiento
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_all_tipo_procedimiento_by_cat($column_name,$value_id);
      $data['_view'] = 'tipo_procedimiento/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- tipo_procedimiento
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Tipo_procedimiento_model->update_tipo_procedimiento($id,$params);
   $data['noof_page'] = 0;
  $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_all_tipo_procedimiento();
  $this->load->view('tipo_procedimiento/index',$data);
}
 }
