<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Tratamiento extends CI_Controller{
     function __construct()
    {
        parent::__construct();
        $this->load->model('Tratamiento_model');
        $this->load->model('Registro_model');
        $this->load->model('Paciente_model');
        $this->load->model('Informe_mensual_model');
        $this->load->model('Certificado_medico_model');
        $this->load->model('Sesion_model');
        $this->load->model('Anemia_glicemia_model');
        
        $this->load->model('Acceso_vascular_model');
        $this->load->model('Medicacion_model');
    }
    
    /*
    * Listing of tratamiento
    */
    public function tratamientos($registro_id)
    {
        try{
            //obtiene los tratamientos de un determinado registro
            $data['registro'] = $this->Registro_model->get_registro($registro_id);
            $data['paciente'] = $this->Tratamiento_model->get_pacienteregistro($registro_id);
            
            $data['_view'] = 'tratamiento/tratamientos';
            $this->load->view('layouts/main',$data);
        } catch (Exception $ex) {
            throw new Exception('Tratamiento Controller : Error in index function - ' . $ex);
        }
    }
    
    function registrar_tratamiento(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'registro_id' => $this->input->post('registro_id'),
                    'tratamiento_mes' => $this->input->post('tratamiento_mes'),
                    'tratamiento_gestion' => $this->input->post('tratamiento_gestion'),
                    'tratamiento_fecha' => $this->input->post('tratamiento_fecha'),
                    'tratamiento_hora' => $this->input->post('tratamiento_hora'),
                );
                $tratamiento_id = $this->Tratamiento_model->add_tratamiento($params);
            echo json_encode($tratamiento_id);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function mostrar_tratamientos(){
        try{
            if($this->input->is_ajax_request()){
                $registro_id = $this->input->post('registro_id');
                $tratamiento = $this->Tratamiento_model->getall_tratamientoregistro($registro_id);
                echo json_encode($tratamiento);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function modificar_tratamiento(){
        try{
            if($this->input->is_ajax_request()){
                $usuario_id = 1;
                $params = array(
                    'tratamiento_mes' => $this->input->post('tratamiento_mes'),
                    'tratamiento_gestion' => $this->input->post('tratamiento_gestion'),
                    'tratamiento_fecha' => $this->input->post('tratamiento_fecha'),
                    'tratamiento_hora' => $this->input->post('tratamiento_hora'),
                );
                $tratamiento_id = $this->input->post('tratamiento_id');
                $this->Tratamiento_model->update_tratamiento($tratamiento_id, $params);
            echo json_encode("ok");
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* regsitra el informe mensual */
    function registrar_infmensual(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'tratamiento_id' => $this->input->post('tratamiento_id'),
                    'infmensual_cabecera' => $this->input->post('infmensual_cabecera'),
                    'infmensual_accesouno' => $this->input->post('infmensual_accesouno'),
                    'infmensual_accesodos' => $this->input->post('infmensual_accesodos'),
                    'infmensual_laboratorio' => $this->input->post('infmensual_laboratorio'),
                    'infmensual_paratohormona' => $this->input->post('infmensual_paratohormona'),
                    'infmensual_glucemia' => $this->input->post('infmensual_glucemia'),
                    'infmensual_firmante' => $this->input->post('infmensual_firmante'),
                    'infmensual_conclusion' => $this->input->post('infmensual_conclusion'),
                    'infmensual_fecha' => $this->input->post('infmensual_fecha'),
                );
                $infmensual_id = $this->Informe_mensual_model->add_informe_mensual($params);
            echo json_encode($infmensual_id);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function get_informemensual(){
        try{
            if($this->input->is_ajax_request()){
                $infmensual_id = $this->input->post('infmensual_id');
                $informe_mensual = $this->Informe_mensual_model->get_informe_mensual($infmensual_id);
                echo json_encode($informe_mensual);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* modificar el informe mensual */
    function modificar_infmensual(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'infmensual_cabecera' => $this->input->post('infmensual_cabecera'),
                    'infmensual_accesouno' => $this->input->post('infmensual_accesouno'),
                    'infmensual_accesodos' => $this->input->post('infmensual_accesodos'),
                    'infmensual_laboratorio' => $this->input->post('infmensual_laboratorio'),
                    'infmensual_paratohormona' => $this->input->post('infmensual_paratohormona'),
                    'infmensual_glucemia' => $this->input->post('infmensual_glucemia'),
                    'infmensual_firmante' => $this->input->post('infmensual_firmante'),
                    'infmensual_conclusion' => $this->input->post('infmensual_conclusion'),
                    'infmensual_fecha' => $this->input->post('infmensual_fecha'),
                );
                $infmensual_id = $this->input->post('infmensual_id');
                $this->Informe_mensual_model->update_informe_mensual($infmensual_id, $params);
            echo json_encode("ok");
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* obtiene el ultimo informe mensual de un tratamiento */
    function obtener_infmensual(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $informe_mensual = $this->Informe_mensual_model->getlast_informepaciente($paciente_id);
            echo json_encode($informe_mensual);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* obtiene el ultimo certificado medico de un tratamiento */
    function obtener_certmedico(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $certificado_paciente = $this->Certificado_medico_model->getlast_certificadopaciente($paciente_id);
            echo json_encode($certificado_paciente);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    /* regsitra el certificado medico */
    function registrar_certmedico(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'certmedico_nombre' => $this->input->post('certmedico_nombre'),
                    'certmedico_codigo' => $this->input->post('certmedico_codigo'),
                    'certmedico_cabecerauno' => $this->input->post('certmedico_cabecerauno'),
                    'certmedico_cabecerados' => $this->input->post('certmedico_cabecerados'),
                    'certmedico_cabeceratres' => $this->input->post('certmedico_cabeceratres'),
                    'certmedico_cabeceracuatro' => $this->input->post('certmedico_cabeceracuatro'),
                    'certmedico_medicacion' => $this->input->post('certmedico_medicacion'),
                    'certmedico_fecha' => $this->input->post('certmedico_fecha'),
                    'tratamiento_id' => $this->input->post('tratamiento_id'),
                );
                $certmedico_id = $this->Certificado_medico_model->add_certificado_medico($params);
            echo json_encode($certmedico_id);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* obtiene los medicamentos de un tratamiento */
    function obtener_medicamentosmes(){
        try{
            if($this->input->is_ajax_request()){
                $tratamiento_id = $this->input->post('tratamiento_id');
                $medicamento_mes = $this->Sesion_model->get_all_sesiontratamiento_mes($tratamiento_id);
                echo json_encode($medicamento_mes);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function get_certificadomedico(){
        try{
            if($this->input->is_ajax_request()){
                $certmedico_id = $this->input->post('certmedico_id');
                $certificado_medico = $this->Certificado_medico_model->get_certificado_medico($certmedico_id);
                echo json_encode($certificado_medico);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
    * muestra los tratamientos de un paciente, despues de la busqueda!.
    */
    public function lostratamientos()
    {
        try{
            $data['_view'] = 'tratamiento/lostratamientos';
            $this->load->view('layouts/main',$data);
        } catch (Exception $ex) {
            throw new Exception('Tratamiento Controller : Error in index function - ' . $ex);
        }
    }
    
    /* busqueda de pacientes de programacion de sesiones */
    function get_pacientes(){
        try{
            if($this->input->is_ajax_request()){
                $filtrar = $this->input->post('filtrar');
                $paciente = $this->Paciente_model->buscar_paciente($filtrar);
                echo json_encode($paciente);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    /* obtiene todos los tratamientos de un paciente */
    function mostrar_tratamientospaciente(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $tratamientos = $this->Tratamiento_model->get_tratamientospaciente($paciente_id);
                echo json_encode($tratamientos);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /* obtiene el registro de un paciente */
    function get_registropaciente(){
        try{
            if($this->input->is_ajax_request()){
                $paciente_id = $this->input->post('paciente_id');
                $registro = $this->Tratamiento_model->get_registropaciente($paciente_id);
                echo json_encode($registro);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function registrar_tratamientosesiones(){
        try{
            if($this->input->is_ajax_request()){
                $sesion_numero = $this->input->post('sesion_numero');
                $sesion_fechainicio = $this->input->post('sesion_fechainicio');
                // 0=>Domingo, 1=>Lunes, 2=>Martes, 3=>Miercoles, 4=>Jueves, 5=>Viernes, 6=>Sabado
                $dia = date("w", strtotime($sesion_fechainicio));
                if($dia >0){
                    
                    $params = array(
                        'registro_id' => $this->input->post('registro_id'),
                        'tratamiento_mes' => $this->input->post('tratamiento_mes'),
                        'tratamiento_gestion' => $this->input->post('tratamiento_gestion'),
                        'tratamiento_fecha' => $this->input->post('tratamiento_fecha'),
                        'tratamiento_hora' => $this->input->post('tratamiento_hora'),
                    );
                    $tratamiento_id = $this->Tratamiento_model->add_tratamiento($params);
                    
                    $registro = $this->Registro_model->get_registro_detratamiento($tratamiento_id);
                    $numero_registro = $registro["registro_numerosesion"];
                    $registro_numaquina = $registro["registro_numaquina"];
                    $registro_tipofiltro = $registro["registro_tipofiltro"];
                    $registro_filtro     = $registro["registro_filtro"];
                    $acceso_vascular = $this->Acceso_vascular_model->get_ultimoa_vascularregistro($registro["registro_id"]);
                    $cateter = "";
                    $fistula = "";
                    if($acceso_vascular["avascular_nombre"] == "Cateter"){
                        $cateter = $acceso_vascular["avascular_detalle"];
                        
                    }else{
                        $fistula = $acceso_vascular["avascular_detalle"];
                    }
                    $lmv = 0;  //0==>false;  1==>true
                    if($dia == 1 || $dia == 3 || $dia == 5){
                        $lmv = 1;
                    }
                    $estado_id = 3; // estado pendiente
                    $num_filtro = 0;
                    $filtro_usado = "";
                    $cont = 1;
                    for($i = 1; $i <= $sesion_numero; $i++){
                        $num_reg    = ($numero_registro+$i);
                        $num_filtro = ($registro_filtro+$cont);
                        $cont++;
                        if($num_filtro == 12){
                            $registro_filtro = 0;
                            $cont = 1;
                        }
                        
                        $params = array(
                            'tratamiento_id' => $tratamiento_id,
                            'sesion_numero' => $i,
                            'sesion_fecha' => $sesion_fechainicio,
                            'sesion_eritropoyetina' => $this->input->post('sesion_eritropoyetina'),
                            'sesion_hierroeve' => $this->input->post('sesion_hierroev'),
                            'sesion_complejobampolla' => $this->input->post('sesion_complejobampolla'),
                            'sesion_costosesion' => $this->input->post('sesion_costosesion'),
                            'sesion_nummaquina' => $registro_numaquina,
                            'sesion_tipofiltro' => $registro_tipofiltro,
                            'sesion_cateter' => $cateter,
                            'sesion_fistula' => $fistula,
                            'sesion_numerosesionhd' => $num_reg,
                            'estado_id' => $estado_id,
                            'avascular_id' => $acceso_vascular["avascular_id"],
                            'sesion_reutlizacionfiltro' => $num_filtro,
                            'sesion_lineasav' => $num_filtro,
                            'sesion_heparina' => 5000,
                        );
                        $sesion_id = $this->Sesion_model->add_sesion($params);
                        
                        if($this->input->post('sesion_eritropoyetina') > 0){
                            $params = array(
                               'sesion_id'=> $sesion_id,
                               'medicamento_id'=> 21, // Jeringa descartable1 ml. c./aguja
                               'estado_id'=> 1,
                               'medicacion_cantidad'=> 1,
                                );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }

                        $dia = date("w", strtotime($sesion_fechainicio));

                        if($lmv == 1){
                            if($dia == 1 || $dia == 3){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+2 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 2,
                                    'sesion_acidofolico' => 2,
                                    'sesion_calcio' => 8,
                                    'sesion_amlodipina' => 4,
                                    'sesion_complejob' => 2,
                                );
                            }elseif($dia == 5){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+3 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 3,
                                    'sesion_acidofolico' => 3,
                                    'sesion_calcio' => 12,
                                    'sesion_amlodipina' => 6,
                                    'sesion_complejob' => 3,
                                );
                            }
                        }else{
                            if($dia == 2 || $dia == 4){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+2 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 2,
                                    'sesion_acidofolico' => 2,
                                    'sesion_calcio' => 8,
                                    'sesion_amlodipina' => 4,
                                    'sesion_complejob' => 2,
                                );
                            }elseif($dia == 6){
                                $sesion_fechainicio = date('Y-m-d', strtotime($sesion_fechainicio."+3 days"));
                                $paramsok = array(
                                    'sesion_omeprazol' => 3,
                                    'sesion_acidofolico' => 3,
                                    'sesion_calcio' => 12,
                                    'sesion_amlodipina' => 6,
                                    'sesion_complejob' => 3,
                                );
                            }
                        }
                        $this->Sesion_model->update_sesion($sesion_id, $paramsok);
                        
                        if($num_filtro == 1){
                            $medicamento_id = 28; // "FILTRO HPS F8/DIACAP/ELISIO 21 H"
                            $cantidad = 1; // es uno porque es al regla del negocio
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> $medicamento_id,
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> $cantidad,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }
                        
                        if($acceso_vascular["avascular_nombre"] == "Cateter"){
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 3, // barbijo descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 4, // Batas descartables
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 8, // Equipo de venoclisis c/aguja Nº 21 G 1 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 10, // Gorro descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 11, // Guantes quirúrgicos descartables Nº 7 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 12, // Guantes descartables Nº 7
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 4,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 13, // Heparina sódica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 17, // Jeringa descartable 20 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 3,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 18, // Jeringa descartable 10 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 19, // Jeringa descartable 5 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 20, // Jeringa descartable3 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 22, // Lineas A-V
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 23, // Solucion Acida
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 24, // Solución Básica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 25, // Solución Fisiologica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            if(($i%2) != 0){
                                $params = array(
                                    'sesion_id'=> $sesion_id,
                                    'medicamento_id'=> 26, // Tela adhesiva micropore 2.5  x 10 m.
                                    'estado_id'=> 1,
                                    'medicacion_cantidad'=> 1,
                                );
                                $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            }
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 27, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 29, // STOPPER IN
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 30, // OTROS INSUMOS CATETER
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }else{
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 2, // Aguja p/fistula arterio-venosa (Par)
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 3, // Barbijo descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 8, // Equipo de venoclisis c/aguja Nº 21 G 1 ½
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 10, // Gorro descartable
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 12, // Guantes descartables Nº 7
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 4,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 13, // Heparina sódica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 17, // Jeringa descartable 20 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 3,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 19, // Jeringa descartable 5 ml. c./aguja
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 22, // Lineas A-V
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 23, // Solucion Acida
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 24, // Solución Básica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 25, // Solución Fisiologica
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 2,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            if(($i%2) != 0){
                                $params = array(
                                    'sesion_id'=> $sesion_id,
                                    'medicamento_id'=> 26, // Tela adhesiva micropore 2.5  x 10 m.
                                    'estado_id'=> 1,
                                    'medicacion_cantidad'=> 1,
                                );
                                $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            }
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 27, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                            $params = array(
                                'sesion_id'=> $sesion_id,
                                'medicamento_id'=> 31, // Transductor para medición de saturación arterial
                                'estado_id'=> 1,
                                'medicacion_cantidad'=> 1,
                            );
                            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
                        }
                        
                    }
                    $params = array(
                        'registro_numerosesion' => $num_reg,
                    );
                    $this->Registro_model->update_registro($registro["registro_id"], $params);
                    
                    $params = array(
                        'registro_filtro' => $num_filtro,
                    );
                    $this->Registro_model->update_registro($registro["registro_id"], $params);
                    
                    echo json_encode("ok");
                }else{
                    echo json_encode("no");
                }
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    /*
     * Deleting tratamiento
     */
    function remove($tratamiento_id)
    {
        $tratamiento = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
        
        // check if the tratamiento exists before trying to delete it
        if(isset($tratamiento['tratamiento_id']))
        {
            $registro_id = $tratamiento['registro_id'];
            $this->Tratamiento_model->delete_tratamiento($tratamiento_id);
            redirect('tratamiento/tratamientos/'.$registro_id);
        }
        else
            show_error('El Tratamiento que intentas eliminar no existe!....');
    }
    
    /* registra el informe mensual de anemia/glicemia */
    function registrar_infanemiaglicemia(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'tratamiento_id' => $this->input->post('tratamiento_id'),
                    'anemiaglic_titulo' => $this->input->post('anemiaglic_titulo'),
                    'anemiaglic_enfermedad' => $this->input->post('anemiaglic_enfermedad'),
                    'anemiaglic_diagnostico' => $this->input->post('anemiaglic_diagnostico'),
                    'anemiaglic_hemoglobina' => $this->input->post('anemiaglic_hemoglobina'),
                    'anemiaglic_hematocrito' => $this->input->post('anemiaglic_hematocrito'),
                    'anemiaglic_administra' => $this->input->post('anemiaglic_administra'),
                    'anemiaglic_fecha' => $this->input->post('anemiaglic_fecha'),
                );
                $anemiaglic_id = $this->Anemia_glicemia_model->add_anemia_glicemia($params);
            echo json_encode($anemiaglic_id);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    
    function get_informeanemiaglicemia(){
        try{
            if($this->input->is_ajax_request()){
                $anemiaglic_id = $this->input->post('anemiaglic_id');
                $anemia_glicemia = $this->Anemia_glicemia_model->get_anemia_glicemia($anemiaglic_id);
                echo json_encode($anemia_glicemia);
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
    /* modificar el informe mensual de Anemia/glicemia */
    function modificar_infanemiaglicemia(){
        try{
            if($this->input->is_ajax_request()){
                $params = array(
                    'anemiaglic_titulo' => $this->input->post('anemiaglic_titulo'),
                    'anemiaglic_enfermedad' => $this->input->post('anemiaglic_enfermedad'),
                    'anemiaglic_diagnostico' => $this->input->post('anemiaglic_diagnostico'),
                    'anemiaglic_hemoglobina' => $this->input->post('anemiaglic_hemoglobina'),
                    'anemiaglic_hematocrito' => $this->input->post('anemiaglic_hematocrito'),
                    'anemiaglic_administra' => $this->input->post('anemiaglic_administra'),
                    'anemiaglic_fecha' => $this->input->post('anemiaglic_fecha'),
                );
                $anemiaglic_id = $this->input->post('anemiaglic_id');
                $this->Anemia_glicemia_model->update_anemia_glicemia($anemiaglic_id, $params);
            echo json_encode("ok");
            }else{                 
                show_404();
            }
        }catch (Exception $e){
            echo 'Ocurrio algo inesperado; revisar datos!. '.$e;
        }
    }
 }
