<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Certificado_medico_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    
    /*
    * Get certificado_medico de un tratamiento determinado
    */ 
    function getall_certificado_medicotratamiento($tratamiento_id)
    {
        try{
            $infmensual = $this->db->query("
                SELECT
                    cm.*
                FROM
                    `certificado_medico` cm
                WHERE
                    cm.tratamiento_id = $tratamiento_id
            ")->row_array();
            
            return $infmensual;
        }catch (Exception $ex){
            throw new Exception('Certificado_medico_model model : Error in getall_certificado_medicotratamiento function - ' . $ex);
        }  
    }
    
    /*
    * Get certificado_medico by certmedico_id 
    */ 
    function get_certificado_medico($certmedico_id)
    {
        try{
           return $this->db->get_where('certificado_medico',array('certmedico_id'=>$certmedico_id))->row_array();
        }catch (Exception $ex) {
           throw new Exception('Certificado_medico_model Model : Error in get_certificado_medico function - ' . $ex);
           }
    }
    
    /*
     * function to add new certificado_medico 
    */
    function add_certificado_medico($params)
    {
        try{
            $this->db->insert('certificado_medico',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Certificado_medico_model model : Error in add_certificado_medico function - ' . $ex);
        }
    }
    
    /* 
     * function to update certificado_medico 
    */
    function update_certificado_medico($certmedico_id,$params)
    {
        try{
            $this->db->where('certmedico_id',$certmedico_id);
            return $this->db->update('certificado_medico',$params);
        }catch (Exception $ex) {
            throw new Exception('Certificado_medico_model model : Error in update_certificado_medico function - ' . $ex);
        }  
    }
    
    /*
    * Get ultimo certificado_medico de un paciente
    */ 
    function getlast_certificadopaciente($paciente_id)
    {
        try{
            $infmensual = $this->db->query("
                SELECT
                    cm.*, r.paciente_id
                FROM
                    `certificado_medico` cm
                left join tratamiento t on t.tratamiento_id = cm.tratamiento_id
                left join registro r on r.registro_id = t.registro_id
                WHERE
                    r.paciente_id = $paciente_id
                order by cm.certmedico_id desc
            ")->row_array();
            
            return $infmensual;
        }catch (Exception $ex){
            throw new Exception('Certificado_medico_model model : Error in getall_certificado_medicotratamiento function - ' . $ex);
        }  
    }
    
 }
