<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Detalle_hora_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get detalle hora
     */
    function get_detalle_hora($detallehora_id)
    {
        $detalle_hora = $this->db->query("
            SELECT
                dh.*
            FROM
                detalle_hora dh
            WHERE
                dh.detallehora_id = $detallehora_id
        ")->row_array();

        return $detalle_hora;
    }
     
    /*
     * Get cantidad de horas registradas de una sesion
     */
    function get_detalle_horasesion_count($sesion_id)
    {
        $detalle_hora = $this->db->query("
            SELECT
                count(*) as numero
            FROM
                detalle_hora dh
            WHERE
                dh.sesion_id = $sesion_id
        ")->row_array();

        return $detalle_hora['numero'];
    }
    /*
       * function to add new detalle hora de una sesion 
    */
    function add_detalle_hora($params)
    {
        try{
            $this->db->insert('detalle_hora',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Detalle_hora model : Error in add_detalle_hora function - ' . $ex);
        }  
    }
    
    /*
     * Get detalle hora de una sesion
     */
    function get_detalle_horasesion($sesion_id)
    {
        $detalle_hora = $this->db->query("
            SELECT
                dh.*, e.estado_color, e.estado_descripcion
            FROM
                detalle_hora dh
            left join estado e on dh.estado_id = e.estado_id
            WHERE
                dh.sesion_id = $sesion_id
        ")->result_array();

        return $detalle_hora;
    }
    
    /* 
    * function to update detalle hora 
    */
    function update_detalle_hora($detallehora_id,$params)
    {
        try{
            $this->db->where('detallehora_id',$detallehora_id);
            return $this->db->update('detalle_hora',$params);
        }catch (Exception $ex){
            throw new Exception('Detalle_hora_model model : Error in update_detalle_hora function - ' . $ex);
        }
    }
    
    /*
     * Get detalle hora activas de una sesion estop para el reporte detalle de procedimiento
     */
    function get_detalle_horasesionactivas($sesion_id)
    {
        $detalle_hora = $this->db->query("
            SELECT
                dh.*, e.estado_color, e.estado_descripcion
            FROM
                detalle_hora dh
            left join estado e on dh.estado_id = e.estado_id
            WHERE
                dh.sesion_id = $sesion_id
                and dh.estado_id = 1
        ")->result_array();

        return $detalle_hora;
    }
    
    /*
     * function to delete registro
     */
    function delete_detallehora($detallehora_id)
    {
        return $this->db->delete('detalle_hora',array('detallehora_id'=>$detallehora_id));
    }
    
 }
