<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Documentacion_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get documentacion by documentacion_id 
      */ 
      function get_documentacion($documentacion_id)
      {
        try{
           return $this->db->get_where('documentacion',array('documentacion_id'=>$documentacion_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model Model : Error in get_documentacion function - ' . $ex);
           }  
      }
      /*
        * Get documentacion by  column name
      */ 
      function get_documentacionbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('documentacion',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model Madel : Error in get_documentacionbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All documentacion count 
      */ 
      function get_all_documentacion_count()
      {
        try{
           $this->db->from('documentacion');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_all_documentacion_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join documentacioncount 
      */ 
      function get_all_with_asso_documentacion()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_all_with_asso_documentacion function - ' . $ex);
           }  
      }
      /*
          * Get all documentacion 
      */ 
      function get_all_documentacion($params = array())
      {
        try{
              $this->db->order_by('documentacion_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('documentacion')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_all_documentacion function - ' . $ex);
           }  
      } 
      /*
         * function to add new documentacion 
      */
      function add_documentacion($params)
      {
        try{
          $this->db->insert('documentacion',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in add_documentacion function - ' . $ex);
           }  
      }
      /* 
          * function to update documentacion 
      */
      function update_documentacion($documentacion_id,$params)
      {
        try{
            $this->db->where('documentacion_id',$documentacion_id);
        return $this->db->update('documentacion',$params);
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in update_documentacion function - ' . $ex);
           }  
       }
     /* 
          * function to delete documentacion 
      */
       function delete_documentacion($documentacion_id)
       {
        try{
             return $this->db->delete('documentacion',array('documentacion_id'=>$documentacion_id));
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in delete_documentacion function - ' . $ex);
           }  
       }
      /*
        * Get documentacion by  column name where not in particular id
      */ 
      function get_documentacionbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('documentacion_id!=', $where_cond);
           return $this->db->get_where('documentacion',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_documentacionbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join documentacioncount 
      */ 
      function get_all_with_asso_documentacion_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_all_with_asso_documentacion_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all documentacion_by_cat 
      */ 
      function get_all_documentacion_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('documentacion_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('documentacion')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Documentacion_model model : Error in get_all_documentacion_by_cat function - ' . $ex);
           }  
      } 
 }
