<?php
/*
  Generated by Manuigniter v2.0
  www.manuigniter.com
 */
class Forma_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get forma by forma_id 
     */
    function get_forma($forma_id) {
        try {
            return $this->db->get_where('forma', array('forma_id' => $forma_id))->row_array();
        } catch (Exception $ex) {
            throw new Exception('Forma_model Model : Error in get_forma function - ' . $ex);
        }
    }

    /*
     * Get all forma 
     */
    function get_all_forma() {
        try {
            $this->db->order_by('forma_nombre', 'asc');
            return $this->db->get('forma')->result_array();
        } catch (Exception $ex) {
            throw new Exception('Forma_model model : Error in get_all_forma function - ' . $ex);
        }
    }

    /*
     * function to add new forma 
     */
    function add_forma($params) {
        try {
            $this->db->insert('forma', $params);
            return $this->db->insert_id();
        } catch (Exception $ex) {
            throw new Exception('Forma_model model : Error in add_forma function - ' . $ex);
        }
    }

    /*
     * function to update forma 
     */
    function update_forma($forma_id, $params) {
        try {
            $this->db->where('forma_id', $forma_id);
            return $this->db->update('forma', $params);
        } catch (Exception $ex) {
            throw new Exception('Forma_model model : Error in update_forma function - ' . $ex);
        }
    }

    /*
     * function to delete forma 
     */
    function delete_forma($forma_id) {
        try {
            return $this->db->delete('forma', array('forma_id' => $forma_id));
        } catch (Exception $ex) {
            throw new Exception('Forma_model model : Error in delete_forma function - ' . $ex);
        }
    }

}
