<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Informe_mensual_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    
    /*
    * Get informe_mensual de un tratamiento determinado
    */ 
    function getall_informe_mensualtratamiento($tratamiento_id)
    {
        try{
            $infmensual = $this->db->query("
                SELECT
                    im.*
                FROM
                    `informe_mensual` im
                WHERE
                    tratamiento_id = $tratamiento_id
            ")->row_array();
            
            return $infmensual;
        }catch (Exception $ex){
            throw new Exception('Informe_mensual_model model : Error in getall_informe_mensualtratamiento function - ' . $ex);
        }  
    }
    
    /*
    * Get informe_mensual by infmensual_id 
    */ 
    function get_informe_mensual($infmensual_id)
    {
        try{
           return $this->db->get_where('informe_mensual',array('infmensual_id'=>$infmensual_id))->row_array();
        }catch (Exception $ex) {
           throw new Exception('Informe_mensual_model Model : Error in get_informe_mensual function - ' . $ex);
           }
    }
    
    /*
     * function to add new informe_mensual 
    */
    function add_informe_mensual($params)
    {
        try{
            $this->db->insert('informe_mensual',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Informe_mensual_model model : Error in add_informe_mensual function - ' . $ex);
        }
    }
    
    /* 
     * function to update informe_mensual 
    */
    function update_informe_mensual($infmensual_id,$params)
    {
        try{
            $this->db->where('infmensual_id',$infmensual_id);
            return $this->db->update('informe_mensual',$params);
        }catch (Exception $ex) {
            throw new Exception('Informe_mensual_model model : Error in update_informe_mensual function - ' . $ex);
        }  
    }
    
 }
