<?php
/*
  Generated by Manuigniter v2.0
  www.manuigniter.com
 */
class Medicacion_model extends CI_Model {
    function __construct() {
        parent::__construct();
    }

    /*
     * Get medicacion by medicacion_id 
     */
    function get_medicacion($medicacion_id) {
        try {
            return $this->db->get_where('medicacion', array('medicacion_id' => $medicacion_id))->row_array();
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model Model : Error in get_medicacion function - ' . $ex);
        }
    }
    
    /*
     * Get medicacion by  column name
     */
    function get_medicacionbyclm_name($clm_name, $clm_value) {
        try {
            return $this->db->get_where('medicacion', array($clm_name => $clm_value))->row_array();
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model Madel : Error in get_medicacionbyclm_name function - ' . $ex);
        }
    }

    /*
     * Get All medicacion count 
     */
    function get_all_medicacion_count() {
        try {
            $this->db->from('medicacion');
            return $this->db->count_all_results();
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in get_all_medicacion_count function - ' . $ex);
        }
    }

    /*
     * Get All with associated tables join medicacioncount 
     */
    function get_all_with_asso_medicacion() {
        try {
            $query = $this->db->get();
            if ($query->num_rows() != 0) {
                return $query->result_array();
            } else {
                return false;
            }
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in get_all_with_asso_medicacion function - ' . $ex);
        }
    }

    /*
     * Get all medicacion 
     */
    function get_all_medicacion($params = array()) {
        try {
            $this->db->order_by('medicacion_id', 'desc');
            if (isset($params) && !empty($params)) {
                $this->db->limit($params['limit'], $params['offset']);
            }
            return $this->db->get('medicacion')->result_array();
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in get_all_medicacion function - ' . $ex);
        }
    }

    /*
     * function to add new medicacion 
     */
    function add_medicacion($params) {
        try {
            $this->db->insert('medicacion', $params);
            return $this->db->insert_id();
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in add_medicacion function - ' . $ex);
        }
    }

    /*
     * function to update medicacion 
     */
    function update_medicacion($medicacion_id, $params) {
        try {
            $this->db->where('medicacion_id', $medicacion_id);
            return $this->db->update('medicacion', $params);
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in update_medicacion function - ' . $ex);
        }
    }

    /*
     * function to delete medicacion 
     */
    function delete_medicacion($medicacion_id) {
        try {
            return $this->db->delete('medicacion', array('medicacion_id' => $medicacion_id));
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in delete_medicacion function - ' . $ex);
        }
    }

    /* Get busqueda medicamentos de una sesion */
    function getall_medicamentosusados($sesion_id) {
        $medicamento = $this->db->query("
            SELECT
                m.*, me.medicacion_id, me.medicacion_cantidad, me.estado_id,
                e.estado_color, e.estado_descripcion
            FROM
                medicamento m
            left join medicacion me on me.medicamento_id = m.medicamento_id
            left join estado e on e.estado_id = me.estado_id
            WHERE
                me.sesion_id = $sesion_id
            ORDER BY m.medicamento_nombre
        ")->result_array();

        return $medicamento;
    }
    /* Get busqueda medicamentos de una sesion */
    function get_medicamento_sesion($sesion_id, $medicamento_id){
        $medicamento = $this->db->query("
            SELECT
                m.*
            FROM
                medicacion m
            WHERE
                m.sesion_id = $sesion_id
                and m.medicamento_id = $medicamento_id
        ")->row_array();
        return $medicamento;
    }
    /*
     * function to delete medicacion determinada de una sesion
     */
    function delete_medicacionsesion($sesion_id, $medicamento_id) {
        try {
            $this->db->query("delete From medicacion
                    where
                        sesion_id = $sesion_id and
                        medicamento_id = $medicamento_id ");
            /*return "delete From medicacion
                    where
                        sesion_id = $sesion_id and
                        medicacion_id = $medicacion_id";*/

            /*$this->db->delete('medicacion', array('medicacion_id' => $medicacion_id, 'sesion_id' => $sesion_id));
            
            $result= $this->db->delete('student');
            return $result;
            */
            /*$this->db->where('sesion_id', $sesion_id);
            $this->db->where('medicacion_id', $medicacion_id);
            $result = $this->db->delete('medicacion');
            return $result;
            /*$medicamento = $this->db->query("
            delete from medicacion
                where
                    sesion_id = $sesion_id and
                    medicacion_id = $medicacion_id
        ");*/
            
            /*$this->db->query($sql);
        return $this->db->insert_id();
            */
            
        //return $medicamento;
        } catch (Exception $ex) {
            throw new Exception('Medicacion_model model : Error in delete_medicacion function - ' . $ex);
        }
    }

}
