<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Medicamento_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get medicamento by medicamento_id 
      */ 
      function get_medicamento($medicamento_id)
      {
        try{
           return $this->db->get_where('medicamento',array('medicamento_id'=>$medicamento_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model Model : Error in get_medicamento function - ' . $ex);
           }  
      }
      /*
        * Get medicamento by  column name
      */ 
      function get_medicamentobyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('medicamento',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model Madel : Error in get_medicamentobyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All medicamento count 
      */ 
      function get_all_medicamento_count()
      {
        try{
           $this->db->from('medicamento');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_all_medicamento_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join medicamentocount 
      */ 
      function get_all_with_asso_medicamento()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_all_with_asso_medicamento function - ' . $ex);
           }  
      }
      /*
          * Get all medicamento 
      */ 
      function get_all_medicamento($params = array())
      {
        try{
              $this->db->order_by('medicamento_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('medicamento')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_all_medicamento function - ' . $ex);
           }  
      } 
      /*
         * function to add new medicamento 
      */
      function add_medicamento($params)
      {
        try{
          $this->db->insert('medicamento',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in add_medicamento function - ' . $ex);
           }  
      }
      /* 
          * function to update medicamento 
      */
      function update_medicamento($medicamento_id,$params)
      {
        try{
            $this->db->where('medicamento_id',$medicamento_id);
        return $this->db->update('medicamento',$params);
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in update_medicamento function - ' . $ex);
           }  
       }
     /* 
          * function to delete medicamento 
      */
       function delete_medicamento($medicamento_id)
       {
        try{
             return $this->db->delete('medicamento',array('medicamento_id'=>$medicamento_id));
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in delete_medicamento function - ' . $ex);
           }  
       }
      /*
        * Get medicamento by  column name where not in particular id
      */ 
      function get_medicamentobyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('medicamento_id!=', $where_cond);
           return $this->db->get_where('medicamento',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_medicamentobyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join medicamentocount 
      */ 
      function get_all_with_asso_medicamento_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_all_with_asso_medicamento_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all medicamento_by_cat 
      */ 
      function get_all_medicamento_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('medicamento_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('medicamento')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Medicamento_model model : Error in get_all_medicamento_by_cat function - ' . $ex);
           }  
      } 
 }
