<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Medicacion_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get medicacion by medicacion_id 
      */ 
      function get_medicacion($medicacion_id)
      {
        try{
           return $this->db->get_where('medicacion',array('medicacion_id'=>$medicacion_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model Model : Error in get_medicacion function - ' . $ex);
           }  
      }
      /*
        * Get medicacion by  column name
      */ 
      function get_medicacionbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('medicacion',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model Madel : Error in get_medicacionbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All medicacion count 
      */ 
      function get_all_medicacion_count()
      {
        try{
           $this->db->from('medicacion');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_all_medicacion_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join medicacioncount 
      */ 
      function get_all_with_asso_medicacion()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_all_with_asso_medicacion function - ' . $ex);
           }  
      }
      /*
          * Get all medicacion 
      */ 
      function get_all_medicacion($params = array())
      {
        try{
              $this->db->order_by('medicacion_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('medicacion')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_all_medicacion function - ' . $ex);
           }  
      } 
      /*
         * function to add new medicacion 
      */
      function add_medicacion($params)
      {
        try{
          $this->db->insert('medicacion',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in add_medicacion function - ' . $ex);
           }  
      }
      /* 
          * function to update medicacion 
      */
      function update_medicacion($medicacion_id,$params)
      {
        try{
            $this->db->where('medicacion_id',$medicacion_id);
        return $this->db->update('medicacion',$params);
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in update_medicacion function - ' . $ex);
           }  
       }
     /* 
          * function to delete medicacion 
      */
       function delete_medicacion($medicacion_id)
       {
        try{
             return $this->db->delete('medicacion',array('medicacion_id'=>$medicacion_id));
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in delete_medicacion function - ' . $ex);
           }  
       }
      /*
        * Get medicacion by  column name where not in particular id
      */ 
      function get_medicacionbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('medicacion_id!=', $where_cond);
           return $this->db->get_where('medicacion',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_medicacionbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join medicacioncount 
      */ 
      function get_all_with_asso_medicacion_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_all_with_asso_medicacion_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all medicacion_by_cat 
      */ 
      function get_all_medicacion_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('medicacion_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('medicacion')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Medicacion_model model : Error in get_all_medicacion_by_cat function - ' . $ex);
           }  
      } 
 }
