<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paciente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get paciente by paciente_id
     */
    function get_paciente($paciente_id)
    {
        $paciente = $this->db->query("
            SELECT
                *

            FROM
                `paciente`

            WHERE
                `paciente_id` = ?
        ",array($paciente_id))->row_array();

        return $paciente;
    }
    
    /*
     * Get paciente by paciente_id
     */
    function get_paciente_inicial()
    {
        $sql = "select 
                0 as paciente_id,
                1 as estado_id,
                1 as genero_id,
                1 as extencion_id,
                'SIN NOMBRE' as paciente_nombre,
                '-' as paciente_codigo,
                0 as paciente_edad,
                'N/A' as paciente_direccion,
                0 as paciente_ci,
                '-' as paciente_celular,
                '-' as paciente_telefono,
                '0' as paciente_nit,
                'SIN NOMBRE' as paciente_razon
                ";
        
        $paciente = $this->db->query($sql)->row_array();
        return $paciente;
    }
    
    /*
     * Get all paciente count
     */
    function get_all_paciente_count()
    {
        $paciente = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `paciente`
        ")->row_array();

        return $paciente['count'];
    }
        
    /*
     * Get all paciente
     */
    function get_all_paciente()
    {
        /*$limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        */
        $paciente = $this->db->query("
            SELECT
                p.*, e.estado_color, e. estado_descripcion, 
                g.genero_nombre, ex.extencion_descripcion
            FROM
                `paciente` p
            left join genero g on p.genero_id = g.genero_id
            left join estado e on p.estado_id = e.estado_id
            left join extencion ex on p.extencion_id = ex.extencion_id
            WHERE
                1 = 1

            ORDER BY p.`paciente_apellido` asc, p.`paciente_nombre` asc

        ")->result_array();

        return $paciente;
    }
        
    /*
     * function to add new paciente
     */
    function add_paciente($params)
    {
        $this->db->insert('paciente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update paciente
     */
    function update_paciente($paciente_id,$params)
    {
        $this->db->where('paciente_id',$paciente_id);
        return $this->db->update('paciente',$params);
    }
    
    /*
     * function to delete paciente
     */
    function delete_paciente($paciente_id)
    {
        $losregistros = $this->db->query("
            SELECT
                r.registro_id
            FROM
                `registro` r
            WHERE
                r.paciente_id = $paciente_id
        ")->result_array();
        
        foreach ($losregistros as $registro) {
            $registro_id = $registro["registro_id"];
            $lostratamientos = $this->db->query("
                SELECT
                    t.tratamiento_id
                FROM
                    `tratamiento` t
                WHERE
                    t.registro_id = $registro_id
            ")->result_array();
            foreach ($lostratamientos as $tratamiento){
                $tratamiento_id = $tratamiento["tratamiento_id"];
                $this->db->delete('certificado_medico',array('tratamiento_id'=>$tratamiento_id));
                $this->db->delete('informe_mensual',array('tratamiento_id'=>$tratamiento_id));
                $this->db->delete('anemia_glicemia',array('tratamiento_id'=>$tratamiento_id));
                
                $lassesiones = $this->db->query("
                    SELECT
                        s.sesion_id
                    FROM
                        `sesion` s
                    WHERE
                        s.tratamiento_id = $tratamiento_id
                ")->result_array();
                foreach ($lassesiones as $sesion){
                    $sesion_id = $sesion["sesion_id"];
                    $this->db->delete('detalle_hora',array('sesion_id'=>$sesion_id));
                    $this->db->delete('medicacion',array('sesion_id'=>$sesion_id));
                }
                
                $this->db->delete('sesion',array('tratamiento_id'=>$tratamiento_id));
                $this->db->delete('tratamiento',array('tratamiento_id'=>$tratamiento_id));
            }
            $this->db->delete('acceso_vascular',array('registro_id'=>$registro_id));
            $this->db->delete('registro',array('registro_id'=>$registro_id));
        }
        return $this->db->delete('paciente',array('paciente_id'=>$paciente_id));
    }
    
    /*
     * buscar el paciente
     */
    function buscar_paciente($parametro)
    {
        $paciente = $this->db->query("
            SELECT
                p.*, e.estado_color, e. estado_descripcion, 
                g.genero_nombre, ex.extencion_descripcion
            FROM
                `paciente` p
            left join genero g on p.genero_id = g.genero_id
            left join estado e on p.estado_id = e.estado_id
            left join extencion ex on p.extencion_id = ex.extencion_id
            WHERE
                p.estado_id = 1
                and(p.paciente_nombre like '%".$parametro."%' or p.paciente_apellido like '%".$parametro."%'
                or p.paciente_ci like '%".$parametro."%')
            ORDER BY p.`paciente_apellido` asc, p.`paciente_nombre` asc

        ")->result_array();

        return $paciente;
    }
    
}
