<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Registro_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get registro by registro_id 
    */ 
    function get_registro($registro_id)
    {
        try{
            return $this->db->get_where('registro',array('registro_id'=>$registro_id))->row_array();
        } catch (Exception $ex) {
            throw new Exception('Registro_model Model : Error in get_registro function - ' . $ex);
        }  
    }
    
    
    function getall_registropaciente($paciente_id)
    {
        try{
            return $this->db->get_where('registro',array('paciente_id'=>$paciente_id))->result_array();
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in get_all_registro function - ' . $ex);
        }  
    }
    
    /*
     * function to add new registro 
    */
    function add_registro($params)
    {
        try{
            $this->db->insert('registro',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in add_registro function - ' . $ex);
        }
    }
    /* 
     * function to update registro 
    */
    function update_registro($registro_id,$params)
    {
        try{
            $this->db->where('registro_id',$registro_id);
            return $this->db->update('registro',$params);
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in update_registro function - ' . $ex);
        }
    }
    /* get registro de un tratamiento */
    function get_registro_detratamiento($tratamiento_id)
    {
        try{
            $num_registro = $this->db->query("
                SELECT
                    r.*
                FROM
                    `registro` r
                left join tratamiento t on r.registro_id = t.registro_id
                WHERE
                    t.tratamiento_id = $tratamiento_id
            ")->row_array();
            
            return $num_registro;
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in get_numeroregistro_detratamiento function - ' . $ex);
        }  
    }
    
    function getlast_registropaciente($paciente_id)
    {
        try{
            $num_registro = $this->db->query("
                SELECT
                    r.*
                FROM
                    `registro` r
                WHERE
                    r.paciente_id = $paciente_id
                order by r.registro_id DESC
            ")->row_array();
            
            return $num_registro;
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in get_all_registro function - ' . $ex);
        }  
    }
    /*
     * function to delete registro
     */
    function delete_registro($registro_id)
    {
        $lostratamientos = $this->db->query("
            SELECT
                t.tratamiento_id
            FROM
                `tratamiento` t
            WHERE
                t.registro_id = $registro_id
        ")->result_array();
        foreach ($lostratamientos as $tratamiento){
            $tratamiento_id = $tratamiento["tratamiento_id"];
            $this->db->delete('certificado_medico',array('tratamiento_id'=>$tratamiento_id));
            $this->db->delete('informe_mensual',array('tratamiento_id'=>$tratamiento_id));
            $this->db->delete('anemia_glicemia',array('tratamiento_id'=>$tratamiento_id));
            
            $lassesiones = $this->db->query("
                SELECT
                    s.sesion_id
                FROM
                    `sesion` s
                WHERE
                    s.tratamiento_id = $tratamiento_id
            ")->result_array();
            foreach ($lassesiones as $sesion){
                $sesion_id = $sesion["sesion_id"];
                $this->db->delete('detalle_hora',array('sesion_id'=>$sesion_id));
                $this->db->delete('medicacion',array('sesion_id'=>$sesion_id));
            }
            
            $this->db->delete('sesion',array('tratamiento_id'=>$tratamiento_id));
            $this->db->delete('tratamiento',array('tratamiento_id'=>$tratamiento_id));
        }
        $this->db->delete('acceso_vascular',array('registro_id'=>$registro_id));
        return $this->db->delete('registro',array('registro_id'=>$registro_id));
    }
    
    /* get ultima sesion de un registro */
    function get_ultimasesion_registro($registro_id)
    {
        try{
            $lasesion = $this->db->query("
                select
                    s.*
                from
                    sesion s
                left join tratamiento t on s.tratamiento_id = t.tratamiento_id
                left join registro r on t.registro_id = r.registro_id
                where r.registro_id = $registro_id
                order by s.sesion_id  desc limit 1
            ")->row_array();
            
            return $lasesion;
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in la ultima sesion function - ' . $ex);
        }  
    }
 }
