<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Registro_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get registro by registro_id 
    */ 
    function get_registro($registro_id)
    {
        try{
            return $this->db->get_where('registro',array('registro_id'=>$registro_id))->row_array();
        } catch (Exception $ex) {
            throw new Exception('Registro_model Model : Error in get_registro function - ' . $ex);
        }  
    }
    
    
    function getall_registropaciente($paciente_id)
    {
        try{
            return $this->db->get_where('registro',array('paciente_id'=>$paciente_id))->result_array();
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in get_all_registro function - ' . $ex);
        }  
    }
    
    /*
     * function to add new registro 
    */
    function add_registro($params)
    {
        try{
            $this->db->insert('registro',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in add_registro function - ' . $ex);
        }
    }
    /* 
     * function to update registro 
    */
    function update_registro($registro_id,$params)
    {
        try{
            $this->db->where('registro_id',$registro_id);
            return $this->db->update('registro',$params);
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in update_registro function - ' . $ex);
        }
    }
    /* get registro de un tratamiento */
    function get_numeroregistro_detratamiento($tratamiento_id)
    {
        try{
            $num_registro = $this->db->query("
                SELECT
                    r.registro_id, r.registro_numero
                FROM
                    `registro` r
                left join tratamiento t on r.registro_id = t.registro_id
                WHERE
                    t.tratamiento_id = $tratamiento_id
            ")->row_array();
            
            return $num_registro;
        }catch (Exception $ex) {
            throw new Exception('Registro_model model : Error in get_numeroregistro_detratamiento function - ' . $ex);
        }  
    }
 }
