<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Tratamiento_model extends CI_Model 
{ 
    function __construct()
    {
        parent::__construct();
    }
    
    /*
    * Get all tratamiento de un registro determinado
    */ 
    function getall_tratamientoregistro($registro_id)
    {
        try{
            $tratamiento = $this->db->query("
                SELECT
                    t.*, im.infmensual_id
                FROM
                    `tratamiento` t
                left join informe_mensual im on t.tratamiento_id = im.tratamiento_id
                WHERE
                    registro_id = $registro_id
            ")->result_array();
            
            return $tratamiento;
        }catch (Exception $ex){
            throw new Exception('Tratamiento_model model : Error in getall_tratamientoregistro function - ' . $ex);
        }  
    }
    
    /*
    * Get tratamiento by tratamiento_id 
    */ 
    function get_tratamiento($tratamiento_id)
    {
        try{
           return $this->db->get_where('tratamiento',array('tratamiento_id'=>$tratamiento_id))->row_array();
        }catch (Exception $ex) {
           throw new Exception('Tratamiento_model Model : Error in get_tratamiento function - ' . $ex);
           }
    }
    
    /*
    * Get tratamiento by tratamiento_id 
    */ 
    function get_pacienteregistro($registro_id)
    {
        try{
            $paciente = $this->db->query("
                SELECT
                    p.*
                FROM
                    `paciente` p
                left join registro r on p.paciente_id = r.paciente_id
                WHERE
                    registro_id = $registro_id
            ")->row_array();
            
            return $paciente;
        }catch (Exception $ex) {
           throw new Exception('Tratamiento_model Model : Error in get_tratamiento function - ' . $ex);
           }
    }
    
    /*
     * function to add new tratamiento 
    */
    function add_tratamiento($params)
    {
        try{
            $this->db->insert('tratamiento',$params);
            return $this->db->insert_id();
        }catch (Exception $ex) {
            throw new Exception('Tratamiento_model model : Error in add_tratamiento function - ' . $ex);
        }
    }
    
    /* 
     * function to update tratamiento 
    */
    function update_tratamiento($tratamiento_id,$params)
    {
        try{
            $this->db->where('tratamiento_id',$tratamiento_id);
            return $this->db->update('tratamiento',$params);
        }catch (Exception $ex) {
            throw new Exception('Tratamiento_model model : Error in update_tratamiento function - ' . $ex);
        }  
    }
      
      
      
      
      
      
      
      
      
      
      /*
        * Get tratamiento by  column name
      */ 
      function get_tratamientobyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('tratamiento',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model Madel : Error in get_tratamientobyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All tratamiento count 
      */ 
      function get_all_tratamiento_count()
      {
        try{
           $this->db->from('tratamiento');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_all_tratamiento_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join tratamientocount 
      */ 
      function get_all_with_asso_tratamiento()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_all_with_asso_tratamiento function - ' . $ex);
           }  
      }
      /*
          * Get all tratamiento 
      */ 
      function get_all_tratamiento($params = array())
      {
        try{
              $this->db->order_by('tratamiento_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('tratamiento')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_all_tratamiento function - ' . $ex);
           }  
      } 
     /* 
          * function to delete tratamiento 
      */
       function delete_tratamiento($tratamiento_id)
       {
        try{
             return $this->db->delete('tratamiento',array('tratamiento_id'=>$tratamiento_id));
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in delete_tratamiento function - ' . $ex);
           }  
       }
      /*
        * Get tratamiento by  column name where not in particular id
      */ 
      function get_tratamientobyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('tratamiento_id!=', $where_cond);
           return $this->db->get_where('tratamiento',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_tratamientobyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join tratamientocount 
      */ 
      function get_all_with_asso_tratamiento_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_all_with_asso_tratamiento_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all tratamiento_by_cat 
      */ 
      function get_all_tratamiento_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('tratamiento_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('tratamiento')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Tratamiento_model model : Error in get_all_tratamiento_by_cat function - ' . $ex);
           }  
      } 
 }
