<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Medicamento extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Medicamento_model');
 } 
 /*
* Listing of medicamento
 */
public function get_all_post()
{
  try{
  $data['medicamento'] = $this->Medicamento_model->get_all_medicamento();
     if($data['medicamento'] && $data['medicamento']!=null){
       $medicamento_ar = array();
       foreach($data['medicamento'] as $m)
       {
       $m_ar = array();
       $m_ar['medicamento_id'] = $m['medicamento_id'];
       $m_ar['medicamento_codigo'] = $m['medicamento_codigo'];
       $m_ar['medicamento_nombre'] = $m['medicamento_nombre'];
       $m_ar['medicamento_forma'] = $m['medicamento_forma'];
       $m_ar['medicamento_concentracion'] = $m['medicamento_concentracion'];
       $m_ar['medicamento_cantidad'] = $m['medicamento_cantidad'];
       $medicamento_ar[] = $m_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $medicamento_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Medicamento controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new medicamento
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'medicamento_codigo'=> $this->input->post('medicamento_codigo'),
       'medicamento_nombre'=> $this->input->post('medicamento_nombre'),
       'medicamento_forma'=> $this->input->post('medicamento_forma'),
       'medicamento_concentracion'=> $this->input->post('medicamento_concentracion'),
       'medicamento_cantidad'=> $this->input->post('medicamento_cantidad'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $medicamento_id= $this->Medicamento_model->add_medicamento($params);
   $data['medicamento'] = $this->Medicamento_model->get_medicamento($medicamento_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Medicamento controller_name : Error in new medicamento function - ' . $ex);
       }  
 }  
  /*
  * Editing a medicamento
 */
  function edit_post($medicamento_id)
 {   
  try{
   $data['medicamento'] = $this->Medicamento_model->get_medicamento($medicamento_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['medicamento']['medicamento_id']))
      {
        $params = array(
           'medicamento_codigo'=> $this->input->post('medicamento_codigo'),
           'medicamento_nombre'=> $this->input->post('medicamento_nombre'),
           'medicamento_forma'=> $this->input->post('medicamento_forma'),
           'medicamento_concentracion'=> $this->input->post('medicamento_concentracion'),
           'medicamento_cantidad'=> $this->input->post('medicamento_cantidad'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Medicamento_model->update_medicamento($medicamento_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $medicamento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $medicamento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Medicamento controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting medicamento
  */
  function remove_post($medicamento_id)
   {
  try{
      $medicamento = $this->Medicamento_model->get_medicamento($medicamento_id);
  // check if the medicamento exists before trying to delete it
       if(isset($medicamento['medicamento_id']))
       {
         $this->Medicamento_model->delete_medicamento($medicamento_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $medicamento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $medicamento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Medicamento controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
