<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Medicacion extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Medicacion_model');
 } 
 /*
* Listing of medicacion
 */
public function get_all_post()
{
  try{
  $data['medicacion'] = $this->Medicacion_model->get_all_medicacion();
     if($data['medicacion'] && $data['medicacion']!=null){
       $medicacion_ar = array();
       foreach($data['medicacion'] as $m)
       {
       $m_ar = array();
       $m_ar['medicacion_id'] = $m['medicacion_id'];
       $m_ar['sesion_id'] = $m['sesion_id'];
       $m_ar['medicamento_id'] = $m['medicamento_id'];
       $m_ar['medicacion_cantidad'] = $m['medicacion_cantidad'];
       $medicacion_ar[] = $m_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $medicacion_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Medicacion controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new medicacion
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'sesion_id'=> $this->input->post('sesion_id'),
       'medicamento_id'=> $this->input->post('medicamento_id'),
       'medicacion_cantidad'=> $this->input->post('medicacion_cantidad'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $medicacion_id= $this->Medicacion_model->add_medicacion($params);
   $data['medicacion'] = $this->Medicacion_model->get_medicacion($medicacion_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Medicacion controller_name : Error in new medicacion function - ' . $ex);
       }  
 }  
  /*
  * Editing a medicacion
 */
  function edit_post($medicacion_id)
 {   
  try{
   $data['medicacion'] = $this->Medicacion_model->get_medicacion($medicacion_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['medicacion']['medicacion_id']))
      {
        $params = array(
           'sesion_id'=> $this->input->post('sesion_id'),
           'medicamento_id'=> $this->input->post('medicamento_id'),
           'medicacion_cantidad'=> $this->input->post('medicacion_cantidad'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Medicacion_model->update_medicacion($medicacion_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $medicacion_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $medicacion_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Medicacion controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting medicacion
  */
  function remove_post($medicacion_id)
   {
  try{
      $medicacion = $this->Medicacion_model->get_medicacion($medicacion_id);
  // check if the medicacion exists before trying to delete it
       if(isset($medicacion['medicacion_id']))
       {
         $this->Medicacion_model->delete_medicacion($medicacion_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $medicacion_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $medicacion_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Medicacion controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
