<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Tipo_procedimiento extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Tipo_procedimiento_model');
 } 
 /*
* Listing of tipo_procedimiento
 */
public function get_all_post()
{
  try{
  $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_all_tipo_procedimiento();
     if($data['tipo_procedimiento'] && $data['tipo_procedimiento']!=null){
       $tipo_procedimiento_ar = array();
       foreach($data['tipo_procedimiento'] as $t)
       {
       $t_ar = array();
       $t_ar['tipoproced_id'] = $t['tipoproced_id'];
       $t_ar['paciente_id'] = $t['paciente_id'];
       $t_ar['tipoproced_nombre'] = $t['tipoproced_nombre'];
       $t_ar['tipoproced_descripcion'] = $t['tipoproced_descripcion'];
       $tipo_procedimiento_ar[] = $t_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $tipo_procedimiento_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Tipo_procedimiento controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new tipo_procedimiento
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'paciente_id'=> $this->input->post('paciente_id'),
       'tipoproced_nombre'=> $this->input->post('tipoproced_nombre'),
       'tipoproced_descripcion'=> $this->input->post('tipoproced_descripcion'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $tipoproced_id= $this->Tipo_procedimiento_model->add_tipo_procedimiento($params);
   $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Tipo_procedimiento controller_name : Error in new tipo_procedimiento function - ' . $ex);
       }  
 }  
  /*
  * Editing a tipo_procedimiento
 */
  function edit_post($tipoproced_id)
 {   
  try{
   $data['tipo_procedimiento'] = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['tipo_procedimiento']['tipoproced_id']))
      {
        $params = array(
           'paciente_id'=> $this->input->post('paciente_id'),
           'tipoproced_nombre'=> $this->input->post('tipoproced_nombre'),
           'tipoproced_descripcion'=> $this->input->post('tipoproced_descripcion'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Tipo_procedimiento_model->update_tipo_procedimiento($tipoproced_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $tipoproced_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $tipoproced_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Tipo_procedimiento controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting tipo_procedimiento
  */
  function remove_post($tipoproced_id)
   {
  try{
      $tipo_procedimiento = $this->Tipo_procedimiento_model->get_tipo_procedimiento($tipoproced_id);
  // check if the tipo_procedimiento exists before trying to delete it
       if(isset($tipo_procedimiento['tipoproced_id']))
       {
         $this->Tipo_procedimiento_model->delete_tipo_procedimiento($tipoproced_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $tipoproced_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $tipoproced_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Tipo_procedimiento controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
