<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Tratamiento extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Tratamiento_model');
 } 
 /*
* Listing of tratamiento
 */
public function get_all_post()
{
  try{
  $data['tratamiento'] = $this->Tratamiento_model->get_all_tratamiento();
     if($data['tratamiento'] && $data['tratamiento']!=null){
       $tratamiento_ar = array();
       foreach($data['tratamiento'] as $t)
       {
       $t_ar = array();
       $t_ar['tratamiento_id'] = $t['tratamiento_id'];
       $t_ar['registro_id'] = $t['registro_id'];
       $t_ar['tratamiento_mes'] = $t['tratamiento_mes'];
       $t_ar['tratamiento_gestion'] = $t['tratamiento_gestion'];
       $t_ar['tratamiento_fecha'] = $t['tratamiento_fecha'];
       $t_ar['tratamiento_hora'] = $t['tratamiento_hora'];
       $tratamiento_ar[] = $t_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $tratamiento_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Tratamiento controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new tratamiento
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'registro_id'=> $this->input->post('registro_id'),
       'tratamiento_mes'=> $this->input->post('tratamiento_mes'),
       'tratamiento_gestion'=> $this->input->post('tratamiento_gestion'),
       'tratamiento_fecha'=> $this->input->post('tratamiento_fecha'),
       'tratamiento_hora'=> $this->input->post('tratamiento_hora'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $tratamiento_id= $this->Tratamiento_model->add_tratamiento($params);
   $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Tratamiento controller_name : Error in new tratamiento function - ' . $ex);
       }  
 }  
  /*
  * Editing a tratamiento
 */
  function edit_post($tratamiento_id)
 {   
  try{
   $data['tratamiento'] = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['tratamiento']['tratamiento_id']))
      {
        $params = array(
           'registro_id'=> $this->input->post('registro_id'),
           'tratamiento_mes'=> $this->input->post('tratamiento_mes'),
           'tratamiento_gestion'=> $this->input->post('tratamiento_gestion'),
           'tratamiento_fecha'=> $this->input->post('tratamiento_fecha'),
           'tratamiento_hora'=> $this->input->post('tratamiento_hora'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Tratamiento_model->update_tratamiento($tratamiento_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $tratamiento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $tratamiento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Tratamiento controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting tratamiento
  */
  function remove_post($tratamiento_id)
   {
  try{
      $tratamiento = $this->Tratamiento_model->get_tratamiento($tratamiento_id);
  // check if the tratamiento exists before trying to delete it
       if(isset($tratamiento['tratamiento_id']))
       {
         $this->Tratamiento_model->delete_tratamiento($tratamiento_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $tratamiento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $tratamiento_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Tratamiento controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
